import type { LayoutSkeleton } from "../../types";

/** 目录 agenda：toc / toc-cards */

/** 目录：图标 + 条目 + 右侧主图（边距 56） */
export const tocLayout: LayoutSkeleton = {
  layoutKey: "toc",
  name: "目录",
  slots: [
    {
      role: "decor",
      elementId: "toc_accent",
      type: "shape",
      x: 56,
      y: 36,
      width: 48,
      height: 5,
      zIndex: 2,
    },
    {
      role: "title",
      elementId: "toc_title",
      type: "text",
      x: 56,
      y: 52,
      width: 480,
      height: 52,
      zIndex: 2,
      maxChars: 16,
    },
    {
      role: "icon",
      elementId: "toc_icon_1",
      type: "icon",
      x: 56,
      y: 140,
      width: 36,
      height: 36,
      zIndex: 2,
      hint: "条目1图标，优先 Aiming",
    },
    {
      role: "bullet",
      elementId: "toc_item_1",
      type: "text",
      x: 108,
      y: 138,
      width: 440,
      height: 48,
      zIndex: 2,
      maxChars: 36,
    },
    {
      role: "icon",
      elementId: "toc_icon_2",
      type: "icon",
      x: 56,
      y: 210,
      width: 36,
      height: 36,
      zIndex: 2,
      hint: "条目2图标，优先 Lightning",
    },
    {
      role: "bullet",
      elementId: "toc_item_2",
      type: "text",
      x: 108,
      y: 208,
      width: 440,
      height: 48,
      zIndex: 2,
      maxChars: 36,
    },
    {
      role: "icon",
      elementId: "toc_icon_3",
      type: "icon",
      x: 56,
      y: 280,
      width: 36,
      height: 36,
      zIndex: 2,
      hint: "条目3图标，优先 ChartHistogram",
    },
    {
      role: "bullet",
      elementId: "toc_item_3",
      type: "text",
      x: 108,
      y: 278,
      width: 440,
      height: 48,
      zIndex: 2,
      maxChars: 36,
    },
    {
      role: "icon",
      elementId: "toc_icon_4",
      type: "icon",
      x: 56,
      y: 350,
      width: 36,
      height: 36,
      zIndex: 2,
      hint: "条目4图标，优先 Success",
    },
    {
      role: "bullet",
      elementId: "toc_item_4",
      type: "text",
      x: 108,
      y: 348,
      width: 440,
      height: 48,
      zIndex: 2,
      maxChars: 36,
    },
    {
      role: "image",
      elementId: "toc_image",
      type: "image",
      x: 600,
      y: 52,
      width: 344,
      height: 460,
      zIndex: 1,
      hint: "目录右侧主图：与主题相关的高端场景摄影，禁止抽象纹理装饰",
    },
  ],
};


/** 目录卡片：四宫格议程卡 */
export const tocCardsLayout: LayoutSkeleton = {
  layoutKey: "toc-cards",
  name: "目录卡片",
  slots: [
    {
      role: "decor",
      elementId: "tc2_accent",
      type: "shape",
      x: 56,
      y: 28,
      width: 48,
      height: 5,
      zIndex: 3,
    },
    {
      role: "icon",
      elementId: "tc2_title_icon",
      type: "icon",
      x: 56,
      y: 44,
      width: 32,
      height: 32,
      zIndex: 4,
      hint: "目录图标，优先 Text",
    },
    {
      role: "title",
      elementId: "tc2_title",
      type: "text",
      x: 100,
      y: 42,
      width: 840,
      height: 48,
      zIndex: 3,
      maxChars: 16,
      hint: "目录/议程",
    },
    // 卡 1
    {
      role: "decor",
      elementId: "tc2_card_1",
      type: "shape",
      x: 56,
      y: 120,
      width: 430,
      height: 180,
      zIndex: 1,
    },
    {
      role: "icon",
      elementId: "tc2_icon_1",
      type: "icon",
      x: 76,
      y: 148,
      width: 28,
      height: 28,
      zIndex: 3,
      hint: "卡1图标，优先 Aiming",
    },
    {
      role: "metric",
      elementId: "tc2_num_1",
      type: "text",
      x: 116,
      y: 140,
      width: 80,
      height: 56,
      zIndex: 2,
      maxChars: 3,
      hint: "01",
    },
    {
      role: "bullet",
      elementId: "tc2_item_1",
      type: "text",
      x: 200,
      y: 148,
      width: 260,
      height: 120,
      zIndex: 2,
      maxChars: 40,
      hint: "结果导向议程条目",
    },
    // 卡 2
    {
      role: "decor",
      elementId: "tc2_card_2",
      type: "shape",
      x: 514,
      y: 120,
      width: 430,
      height: 180,
      zIndex: 1,
    },
    {
      role: "icon",
      elementId: "tc2_icon_2",
      type: "icon",
      x: 534,
      y: 148,
      width: 28,
      height: 28,
      zIndex: 3,
      hint: "卡2图标，优先 Lightning",
    },
    {
      role: "metric",
      elementId: "tc2_num_2",
      type: "text",
      x: 574,
      y: 140,
      width: 80,
      height: 56,
      zIndex: 2,
      maxChars: 3,
      hint: "02",
    },
    {
      role: "bullet",
      elementId: "tc2_item_2",
      type: "text",
      x: 658,
      y: 148,
      width: 260,
      height: 120,
      zIndex: 2,
      maxChars: 40,
    },
    // 卡 3
    {
      role: "decor",
      elementId: "tc2_card_3",
      type: "shape",
      x: 56,
      y: 324,
      width: 430,
      height: 180,
      zIndex: 1,
    },
    {
      role: "icon",
      elementId: "tc2_icon_3",
      type: "icon",
      x: 76,
      y: 352,
      width: 28,
      height: 28,
      zIndex: 3,
      hint: "卡3图标，优先 ChartHistogram",
    },
    {
      role: "metric",
      elementId: "tc2_num_3",
      type: "text",
      x: 116,
      y: 344,
      width: 80,
      height: 56,
      zIndex: 2,
      maxChars: 3,
      hint: "03",
    },
    {
      role: "bullet",
      elementId: "tc2_item_3",
      type: "text",
      x: 200,
      y: 352,
      width: 260,
      height: 120,
      zIndex: 2,
      maxChars: 40,
    },
    // 卡 4
    {
      role: "decor",
      elementId: "tc2_card_4",
      type: "shape",
      x: 514,
      y: 324,
      width: 430,
      height: 180,
      zIndex: 1,
    },
    {
      role: "icon",
      elementId: "tc2_icon_4",
      type: "icon",
      x: 534,
      y: 352,
      width: 28,
      height: 28,
      zIndex: 3,
      hint: "卡4图标，优先 Success",
    },
    {
      role: "metric",
      elementId: "tc2_num_4",
      type: "text",
      x: 574,
      y: 344,
      width: 80,
      height: 56,
      zIndex: 2,
      maxChars: 3,
      hint: "04",
    },
    {
      role: "bullet",
      elementId: "tc2_item_4",
      type: "text",
      x: 658,
      y: 352,
      width: 260,
      height: 120,
      zIndex: 2,
      maxChars: 40,
    },
  ],
};

