import type { LayoutSkeleton } from "../../types";

/** 留白 breath：quote / quote-center */

/** 引用页：图标装饰 + 引语 + 署名 + 侧图 */
export const quoteLayout: LayoutSkeleton = {
  layoutKey: "quote",
  name: "引用留白",
  slots: [
    {
      role: "icon",
      elementId: "qt_icon",
      type: "icon",
      x: 72,
      y: 72,
      width: 40,
      height: 40,
      zIndex: 3,
      hint: "引用页图标，优先 Star 或 Like",
    },
    {
      role: "decor",
      elementId: "qt_mark",
      type: "shape",
      x: 128,
      y: 84,
      width: 24,
      height: 24,
      zIndex: 2,
      hint: "点缀形，优先 diamond",
    },
    {
      role: "body",
      elementId: "qt_quote",
      type: "text",
      x: 72,
      y: 140,
      width: 520,
      height: 240,
      zIndex: 2,
      maxChars: 80,
      hint: "一句有力引语/核心主张，含数字或对比更好",
    },
    {
      role: "decor",
      elementId: "qt_line",
      type: "shape",
      x: 72,
      y: 400,
      width: 64,
      height: 4,
      zIndex: 2,
      hint: "署名上方短线",
    },
    {
      role: "subtitle",
      elementId: "qt_attr",
      type: "text",
      x: 72,
      y: 420,
      width: 480,
      height: 48,
      zIndex: 2,
      maxChars: 36,
      hint: "署名或来源，如 — 客户名 / 角色",
    },
    {
      role: "image",
      elementId: "qt_image",
      type: "image",
      x: 640,
      y: 72,
      width: 300,
      height: 420,
      zIndex: 1,
      hint: "与引语气质一致的人物/场景肖像，禁止抽象纹理",
    },
  ],
};

/** 居中引用：图标 + 双点缀 + 全宽留白 */
export const quoteCenterLayout: LayoutSkeleton = {
  layoutKey: "quote-center",
  name: "居中引用",
  slots: [
    {
      role: "decor",
      elementId: "qc_dot_l",
      type: "shape",
      x: 420,
      y: 100,
      width: 14,
      height: 14,
      zIndex: 2,
      hint: "左侧点缀，oval",
    },
    {
      role: "icon",
      elementId: "qc_icon",
      type: "icon",
      x: 478,
      y: 88,
      width: 44,
      height: 44,
      zIndex: 3,
      hint: "居中引用图标，优先 Star",
    },
    {
      role: "decor",
      elementId: "qc_dot_r",
      type: "shape",
      x: 566,
      y: 100,
      width: 14,
      height: 14,
      zIndex: 2,
      hint: "右侧点缀，oval",
    },
    {
      role: "body",
      elementId: "qc_quote",
      type: "text",
      x: 120,
      y: 170,
      width: 760,
      height: 200,
      zIndex: 2,
      maxChars: 72,
      hint: "一句有力主张/客户证言",
    },
    {
      role: "decor",
      elementId: "qc_line",
      type: "shape",
      x: 460,
      y: 400,
      width: 80,
      height: 4,
      zIndex: 2,
    },
    {
      role: "subtitle",
      elementId: "qc_attr",
      type: "text",
      x: 200,
      y: 420,
      width: 600,
      height: 48,
      zIndex: 2,
      maxChars: 36,
      hint: "— 署名 / 来源",
    },
  ],
};
