import type { LayoutSkeleton } from "../../types";

/** 封底 close：ending / ending-center */

/** 封底：全幅图 + 图标 + 致谢 */
export const endingLayout: LayoutSkeleton = {
  layoutKey: "ending",
  name: "封底",
  slots: [
    {
      role: "image",
      elementId: "end_image",
      type: "image",
      x: 0,
      y: 0,
      width: 1000,
      height: 562,
      zIndex: 0,
      hint: "全幅氛围图，偏暗中调，中部/左下留叠字暗区",
    },
    {
      role: "icon",
      elementId: "end_icon",
      type: "icon",
      x: 56,
      y: 180,
      width: 40,
      height: 40,
      zIndex: 3,
      hint: "封底图标，优先 Like / Success",
    },
    {
      role: "decor",
      elementId: "end_accent",
      type: "shape",
      x: 108,
      y: 196,
      width: 48,
      height: 6,
      zIndex: 2,
    },
    {
      role: "title",
      elementId: "end_title",
      type: "text",
      x: 56,
      y: 240,
      width: 800,
      height: 110,
      zIndex: 2,
      maxChars: 24,
      hint: "谢谢 / 下一步",
    },
    {
      role: "subtitle",
      elementId: "end_subtitle",
      type: "text",
      x: 56,
      y: 380,
      width: 720,
      height: 72,
      zIndex: 2,
      maxChars: 48,
      hint: "联系方式或行动号召",
    },
  ],
};

/** 居中封底：图标 + 居中致谢 */
export const endingCenterLayout: LayoutSkeleton = {
  layoutKey: "ending-center",
  name: "居中封底",
  slots: [
    {
      role: "image",
      elementId: "ec_image",
      type: "image",
      x: 0,
      y: 0,
      width: 1000,
      height: 562,
      zIndex: 0,
      hint: "全幅氛围图，偏暗中调，中部留叠字暗区",
    },
    {
      role: "icon",
      elementId: "ec_icon",
      type: "icon",
      x: 478,
      y: 150,
      width: 44,
      height: 44,
      zIndex: 3,
      hint: "居中封底图标，优先 Like",
    },
    {
      role: "decor",
      elementId: "ec_accent",
      type: "shape",
      x: 472,
      y: 210,
      width: 56,
      height: 6,
      zIndex: 2,
    },
    {
      role: "title",
      elementId: "ec_title",
      type: "text",
      x: 120,
      y: 236,
      width: 760,
      height: 100,
      zIndex: 2,
      maxChars: 20,
      hint: "谢谢 / Q&A / 下一步",
    },
    {
      role: "subtitle",
      elementId: "ec_subtitle",
      type: "text",
      x: 160,
      y: 360,
      width: 680,
      height: 72,
      zIndex: 2,
      maxChars: 48,
      hint: "联系方式或行动号召",
    },
  ],
};
