import type { LayoutSkeleton } from "../../types";

/** 对比 compare：table / compare-split */

/** 数据表格页：标题 + 主表格 + 侧栏说明图 */
export const tableLayout: LayoutSkeleton = {
  layoutKey: "table",
  name: "数据表格",
  slots: [
    {
      role: "decor",
      elementId: "tb_accent",
      type: "shape",
      x: 56,
      y: 28,
      width: 48,
      height: 5,
      zIndex: 2,
    },
    {
      role: "icon",
      elementId: "tb_icon",
      type: "icon",
      x: 56,
      y: 40,
      width: 32,
      height: 32,
      zIndex: 3,
      hint: "表格页图标，优先 TableFile",
    },
    {
      role: "title",
      elementId: "tb_title",
      type: "text",
      x: 100,
      y: 38,
      width: 520,
      height: 56,
      zIndex: 2,
      maxChars: 30,
    },
    {
      role: "table",
      elementId: "tb_table",
      type: "table",
      x: 40,
      y: 110,
      width: 580,
      height: 400,
      zIndex: 1,
      hint: "对比/指标表：headers + rows，3～6 列、3～7 行数据，≤10×10",
    },
    {
      role: "image",
      elementId: "tb_image",
      type: "image",
      x: 650,
      y: 42,
      width: 290,
      height: 400,
      zIndex: 1,
      hint: "与本页表格主题相关的场景图，禁止抽象纹理装饰",
    },
    {
      role: "icon",
      elementId: "tb_side_icon",
      type: "icon",
      x: 650,
      y: 460,
      width: 28,
      height: 28,
      zIndex: 3,
      hint: "侧栏脚注图标，优先 Aiming",
    },
    {
      role: "bullet",
      elementId: "tb_side_note",
      type: "text",
      x: 690,
      y: 460,
      width: 250,
      height: 32,
      zIndex: 2,
      maxChars: 18,
      hint: "侧栏短注",
    },
  ],
};


/** 左右对比：标题 + 双栏正文（非表格），适合竞品/方案对照 */
export const compareSplitLayout: LayoutSkeleton = {
  layoutKey: "compare-split",
  name: "左右对比",
  slots: [
    {
      role: "decor",
      elementId: "cs_accent",
      type: "shape",
      x: 56,
      y: 28,
      width: 48,
      height: 5,
      zIndex: 2,
    },
    {
      role: "icon",
      elementId: "cs_icon",
      type: "icon",
      x: 56,
      y: 40,
      width: 32,
      height: 32,
      zIndex: 3,
      hint: "对比页图标，优先 Aiming",
    },
    {
      role: "title",
      elementId: "cs_title",
      type: "text",
      x: 100,
      y: 38,
      width: 844,
      height: 48,
      zIndex: 2,
      maxChars: 30,
    },
    {
      role: "decor",
      elementId: "cs_card_l",
      type: "shape",
      x: 56,
      y: 120,
      width: 430,
      height: 380,
      zIndex: 1,
    },
    {
      role: "icon",
      elementId: "cs_icon_l",
      type: "icon",
      x: 80,
      y: 144,
      width: 32,
      height: 32,
      zIndex: 3,
      hint: "左侧图标，优先 Success",
    },
    {
      role: "subtitle",
      elementId: "cs_head_l",
      type: "text",
      x: 124,
      y: 144,
      width: 340,
      height: 44,
      zIndex: 2,
      maxChars: 18,
      hint: "左侧方案名，如「我们」",
    },
    {
      role: "body",
      elementId: "cs_body_l",
      type: "text",
      x: 80,
      y: 208,
      width: 382,
      height: 260,
      zIndex: 2,
      maxChars: 160,
      hint: "优势要点，含数字",
    },
    {
      role: "decor",
      elementId: "cs_card_r",
      type: "shape",
      x: 514,
      y: 120,
      width: 430,
      height: 380,
      zIndex: 1,
    },
    {
      role: "icon",
      elementId: "cs_icon_r",
      type: "icon",
      x: 538,
      y: 144,
      width: 32,
      height: 32,
      zIndex: 3,
      hint: "右侧图标，优先 Setting",
    },
    {
      role: "subtitle",
      elementId: "cs_head_r",
      type: "text",
      x: 582,
      y: 144,
      width: 340,
      height: 44,
      zIndex: 2,
      maxChars: 18,
      hint: "右侧对照名，如「传统方案」",
    },
    {
      role: "body",
      elementId: "cs_body_r",
      type: "text",
      x: 538,
      y: 208,
      width: 382,
      height: 260,
      zIndex: 2,
      maxChars: 160,
      hint: "对照要点",
    },
  ],
};

