import type { LayoutSkeleton } from "../../types";

/** 数据证据 evidence：chart / chart-wide */

/** 数据图表：左图右解读图，边距对齐 */
export const chartLayout: LayoutSkeleton = {
  layoutKey: "chart",
  name: "数据图表",
  slots: [
    {
      role: "decor",
      elementId: "ch_accent",
      type: "shape",
      x: 56,
      y: 28,
      width: 48,
      height: 5,
      zIndex: 2,
    },
    {
      role: "icon",
      elementId: "ch_icon",
      type: "icon",
      x: 56,
      y: 40,
      width: 32,
      height: 32,
      zIndex: 3,
      hint: "图表页图标，优先 ChartHistogram",
    },
    {
      role: "title",
      elementId: "ch_title",
      type: "text",
      x: 100,
      y: 38,
      width: 516,
      height: 56,
      zIndex: 2,
      maxChars: 30,
    },
    {
      role: "chart",
      elementId: "ch_chart",
      type: "chart",
      x: 56,
      y: 110,
      width: 560,
      height: 400,
      zIndex: 1,
      hint: "图表数据",
    },
    {
      role: "image",
      elementId: "ch_image",
      type: "image",
      x: 640,
      y: 48,
      width: 304,
      height: 400,
      zIndex: 1,
      hint: "与本页指标/业务相关的场景图，禁止抽象纹理装饰",
    },
    {
      role: "icon",
      elementId: "ch_badge",
      type: "icon",
      x: 640,
      y: 468,
      width: 28,
      height: 28,
      zIndex: 3,
      hint: "图下角装饰图标，优先 Aiming",
    },
    {
      role: "bullet",
      elementId: "ch_caption",
      type: "text",
      x: 680,
      y: 468,
      width: 260,
      height: 32,
      zIndex: 2,
      maxChars: 20,
      hint: "图注短句",
    },
  ],
};


/** 全宽图表：标题 + 通栏图表，适合数据主叙事 */
export const chartWideLayout: LayoutSkeleton = {
  layoutKey: "chart-wide",
  name: "全宽图表",
  slots: [
    {
      role: "decor",
      elementId: "cw_accent",
      type: "shape",
      x: 56,
      y: 28,
      width: 48,
      height: 5,
      zIndex: 2,
    },
    {
      role: "icon",
      elementId: "cw_icon",
      type: "icon",
      x: 56,
      y: 36,
      width: 32,
      height: 32,
      zIndex: 3,
      hint: "全宽图表图标，优先 ChartHistogram",
    },
    {
      role: "title",
      elementId: "cw_title",
      type: "text",
      x: 100,
      y: 34,
      width: 840,
      height: 52,
      zIndex: 2,
      maxChars: 36,
    },
    {
      role: "subtitle",
      elementId: "cw_note",
      type: "text",
      x: 56,
      y: 100,
      width: 880,
      height: 36,
      zIndex: 2,
      maxChars: 60,
      hint: "一句数据解读或时间范围说明",
    },
    {
      role: "decor",
      elementId: "cw_dot_1",
      type: "shape",
      x: 56,
      y: 140,
      width: 8,
      height: 8,
      zIndex: 2,
      hint: "装饰点 oval",
    },
    {
      role: "decor",
      elementId: "cw_dot_2",
      type: "shape",
      x: 72,
      y: 140,
      width: 8,
      height: 8,
      zIndex: 2,
      hint: "装饰点 oval",
    },
    {
      role: "chart",
      elementId: "cw_chart",
      type: "chart",
      x: 48,
      y: 160,
      width: 904,
      height: 350,
      zIndex: 1,
      hint: "通栏图表，4～6 项具体数据",
    },
  ],
};

