import type { LayoutSkeleton } from "../../types";

/** 封面 hero：cover / cover-center / cover-left / cover-right */

/** 封面：全幅主图 + 品牌图标 + 左下标题 */
export const coverLayout: LayoutSkeleton = {
  layoutKey: "cover",
  name: "封面",
  slots: [
    {
      role: "image",
      elementId: "cover_image",
      type: "image",
      x: 0,
      y: 0,
      width: 1000,
      height: 562,
      zIndex: 0,
      hint: "全幅氛围图，偏暗中调，左下留叠字暗区",
    },
    {
      role: "icon",
      elementId: "cover_badge",
      type: "icon",
      x: 56,
      y: 240,
      width: 36,
      height: 36,
      zIndex: 3,
      hint: "品牌角标图标，优先 DiamondThree 或 Star",
    },
    {
      role: "decor",
      elementId: "cover_accent",
      type: "shape",
      x: 104,
      y: 254,
      width: 48,
      height: 6,
      zIndex: 2,
      hint: "品牌强调条",
    },
    {
      role: "title",
      elementId: "cover_title",
      type: "text",
      x: 56,
      y: 300,
      width: 800,
      height: 120,
      zIndex: 2,
      maxChars: 28,
      hint: "主标题（可两行）",
    },
    {
      role: "subtitle",
      elementId: "cover_subtitle",
      type: "text",
      x: 56,
      y: 440,
      width: 720,
      height: 56,
      zIndex: 2,
      maxChars: 48,
      hint: "副标题：定位 + 关键信息",
    },
  ],
};

/** 居中封面：图标 + 强调条 + 居中标题 */
export const coverCenterLayout: LayoutSkeleton = {
  layoutKey: "cover-center",
  name: "居中封面",
  slots: [
    {
      role: "image",
      elementId: "cc_image",
      type: "image",
      x: 0,
      y: 0,
      width: 1000,
      height: 562,
      zIndex: 0,
      hint: "全幅氛围图，偏暗中调，中部留叠字暗区",
    },
    {
      role: "icon",
      elementId: "cc_badge",
      type: "icon",
      x: 478,
      y: 148,
      width: 44,
      height: 44,
      zIndex: 3,
      hint: "居中品牌图标，优先 DiamondThree",
    },
    {
      role: "decor",
      elementId: "cc_accent",
      type: "shape",
      x: 472,
      y: 208,
      width: 56,
      height: 6,
      zIndex: 2,
      hint: "居中品牌强调条",
    },
    {
      role: "title",
      elementId: "cc_title",
      type: "text",
      x: 120,
      y: 232,
      width: 760,
      height: 120,
      zIndex: 2,
      maxChars: 24,
      hint: "居中主标题（可两行）",
    },
    {
      role: "subtitle",
      elementId: "cc_subtitle",
      type: "text",
      x: 160,
      y: 380,
      width: 680,
      height: 56,
      zIndex: 2,
      maxChars: 48,
      hint: "居中副标题：定位 + 关键信息",
    },
  ],
};

/** 左图右文：左半幅图 + 右侧标题/副标题 */
export const coverLeftLayout: LayoutSkeleton = {
  layoutKey: "cover-left",
  name: "左图封面",
  slots: [
    {
      role: "image",
      elementId: "cl_image",
      type: "image",
      x: 0,
      y: 0,
      width: 500,
      height: 562,
      zIndex: 0,
      hint: "左半幅竖构图，满高，干净浅亮，禁止叠字暗区",
    },
    {
      role: "icon",
      elementId: "cl_badge",
      type: "icon",
      x: 556,
      y: 180,
      width: 36,
      height: 36,
      zIndex: 3,
      hint: "品牌角标图标，优先 DiamondThree 或 Star",
    },
    {
      role: "decor",
      elementId: "cl_accent",
      type: "shape",
      x: 604,
      y: 194,
      width: 48,
      height: 6,
      zIndex: 2,
      hint: "品牌强调条",
    },
    {
      role: "title",
      elementId: "cl_title",
      type: "text",
      x: 556,
      y: 240,
      width: 388,
      height: 120,
      zIndex: 2,
      maxChars: 24,
      hint: "主标题（可两行）",
    },
    {
      role: "subtitle",
      elementId: "cl_subtitle",
      type: "text",
      x: 556,
      y: 380,
      width: 388,
      height: 72,
      zIndex: 2,
      maxChars: 48,
      hint: "副标题：定位 + 关键信息",
    },
  ],
};

/** 右图左文：右半幅图 + 左侧标题/副标题 */
export const coverRightLayout: LayoutSkeleton = {
  layoutKey: "cover-right",
  name: "右图封面",
  slots: [
    {
      role: "image",
      elementId: "cr_image",
      type: "image",
      x: 500,
      y: 0,
      width: 500,
      height: 562,
      zIndex: 0,
      hint: "右半幅竖构图，满高，干净浅亮，禁止叠字暗区",
    },
    {
      role: "icon",
      elementId: "cr_badge",
      type: "icon",
      x: 56,
      y: 180,
      width: 36,
      height: 36,
      zIndex: 3,
      hint: "品牌角标图标，优先 DiamondThree 或 Star",
    },
    {
      role: "decor",
      elementId: "cr_accent",
      type: "shape",
      x: 104,
      y: 194,
      width: 48,
      height: 6,
      zIndex: 2,
      hint: "品牌强调条",
    },
    {
      role: "title",
      elementId: "cr_title",
      type: "text",
      x: 56,
      y: 240,
      width: 388,
      height: 120,
      zIndex: 2,
      maxChars: 24,
      hint: "主标题（可两行）",
    },
    {
      role: "subtitle",
      elementId: "cr_subtitle",
      type: "text",
      x: 56,
      y: 380,
      width: 388,
      height: 72,
      zIndex: 2,
      maxChars: 48,
      hint: "副标题：定位 + 关键信息",
    },
  ],
};
