import type { LayoutSkeleton } from "../../types";

/** 指标 metrics：kpi / kpi-row */

/** 大数字 KPI：三列指标卡（底板 shape + 大数字 + 说明） */
export const kpiLayout: LayoutSkeleton = {
  layoutKey: "kpi",
  name: "大数字指标",
  slots: [
    {
      role: "decor",
      elementId: "kpi_accent",
      type: "shape",
      x: 56,
      y: 36,
      width: 48,
      height: 5,
      zIndex: 3,
    },
    {
      role: "icon",
      elementId: "kpi_title_icon",
      type: "icon",
      x: 56,
      y: 48,
      width: 32,
      height: 32,
      zIndex: 4,
      hint: "指标页图标，优先 ChartHistogram",
    },
    {
      role: "title",
      elementId: "kpi_title",
      type: "text",
      x: 100,
      y: 48,
      width: 840,
      height: 52,
      zIndex: 3,
      maxChars: 28,
      hint: "本页指标主题，具体可感知",
    },
    // 卡 1
    {
      role: "decor",
      elementId: "kpi_card_1",
      type: "shape",
      x: 56,
      y: 130,
      width: 280,
      height: 340,
      zIndex: 1,
      hint: "指标卡底板",
    },
    {
      role: "icon",
      elementId: "kpi_icon_1",
      type: "icon",
      x: 76,
      y: 152,
      width: 32,
      height: 32,
      zIndex: 3,
      hint: "卡1图标，优先 Lightning",
    },
    {
      role: "metric",
      elementId: "kpi_metric_1",
      type: "text",
      x: 76,
      y: 200,
      width: 240,
      height: 90,
      zIndex: 2,
      maxChars: 10,
      hint: "大数字，如 128% / ￥2.4亿",
    },
    {
      role: "bullet",
      elementId: "kpi_label_1",
      type: "text",
      x: 76,
      y: 310,
      width: 240,
      height: 120,
      zIndex: 2,
      maxChars: 48,
      hint: "指标名 + 一句解读",
    },
    // 卡 2
    {
      role: "decor",
      elementId: "kpi_card_2",
      type: "shape",
      x: 360,
      y: 130,
      width: 280,
      height: 340,
      zIndex: 1,
      hint: "指标卡底板",
    },
    {
      role: "icon",
      elementId: "kpi_icon_2",
      type: "icon",
      x: 380,
      y: 152,
      width: 32,
      height: 32,
      zIndex: 3,
      hint: "卡2图标，优先 Aiming",
    },
    {
      role: "metric",
      elementId: "kpi_metric_2",
      type: "text",
      x: 380,
      y: 200,
      width: 240,
      height: 90,
      zIndex: 2,
      maxChars: 10,
      hint: "大数字",
    },
    {
      role: "bullet",
      elementId: "kpi_label_2",
      type: "text",
      x: 380,
      y: 310,
      width: 240,
      height: 120,
      zIndex: 2,
      maxChars: 48,
      hint: "指标名 + 一句解读",
    },
    // 卡 3
    {
      role: "decor",
      elementId: "kpi_card_3",
      type: "shape",
      x: 664,
      y: 130,
      width: 280,
      height: 340,
      zIndex: 1,
      hint: "指标卡底板",
    },
    {
      role: "icon",
      elementId: "kpi_icon_3",
      type: "icon",
      x: 684,
      y: 152,
      width: 32,
      height: 32,
      zIndex: 3,
      hint: "卡3图标，优先 Success",
    },
    {
      role: "metric",
      elementId: "kpi_metric_3",
      type: "text",
      x: 684,
      y: 200,
      width: 240,
      height: 90,
      zIndex: 2,
      maxChars: 10,
      hint: "大数字",
    },
    {
      role: "bullet",
      elementId: "kpi_label_3",
      type: "text",
      x: 684,
      y: 310,
      width: 240,
      height: 120,
      zIndex: 2,
      maxChars: 48,
      hint: "指标名 + 一句解读",
    },
  ],
};


/** 横排 KPI：四个指标横条，适合一排关键数字 */
export const kpiRowLayout: LayoutSkeleton = {
  layoutKey: "kpi-row",
  name: "横排指标",
  slots: [
    {
      role: "decor",
      elementId: "kr_accent",
      type: "shape",
      x: 56,
      y: 36,
      width: 48,
      height: 5,
      zIndex: 3,
    },
    {
      role: "icon",
      elementId: "kr_title_icon",
      type: "icon",
      x: 56,
      y: 52,
      width: 32,
      height: 32,
      zIndex: 4,
      hint: "指标页图标，优先 ChartHistogram",
    },
    {
      role: "title",
      elementId: "kr_title",
      type: "text",
      x: 100,
      y: 52,
      width: 840,
      height: 52,
      zIndex: 3,
      maxChars: 28,
    },
    {
      role: "subtitle",
      elementId: "kr_note",
      type: "text",
      x: 56,
      y: 112,
      width: 880,
      height: 40,
      zIndex: 3,
      maxChars: 56,
      hint: "时间范围或数据来源说明",
    },
    // 4 metrics
    {
      role: "decor",
      elementId: "kr_card_1",
      type: "shape",
      x: 56,
      y: 180,
      width: 210,
      height: 280,
      zIndex: 1,
    },
    {
      role: "icon",
      elementId: "kr_icon_1",
      type: "icon",
      x: 72,
      y: 200,
      width: 28,
      height: 28,
      zIndex: 3,
      hint: "卡1图标，优先 Lightning",
    },
    {
      role: "metric",
      elementId: "kr_metric_1",
      type: "text",
      x: 72,
      y: 244,
      width: 178,
      height: 80,
      zIndex: 2,
      maxChars: 10,
    },
    {
      role: "bullet",
      elementId: "kr_label_1",
      type: "text",
      x: 72,
      y: 340,
      width: 178,
      height: 96,
      zIndex: 2,
      maxChars: 36,
    },
    {
      role: "decor",
      elementId: "kr_card_2",
      type: "shape",
      x: 282,
      y: 180,
      width: 210,
      height: 280,
      zIndex: 1,
    },
    {
      role: "icon",
      elementId: "kr_icon_2",
      type: "icon",
      x: 298,
      y: 200,
      width: 28,
      height: 28,
      zIndex: 3,
      hint: "卡2图标，优先 Aiming",
    },
    {
      role: "metric",
      elementId: "kr_metric_2",
      type: "text",
      x: 298,
      y: 244,
      width: 178,
      height: 80,
      zIndex: 2,
      maxChars: 10,
    },
    {
      role: "bullet",
      elementId: "kr_label_2",
      type: "text",
      x: 298,
      y: 340,
      width: 178,
      height: 96,
      zIndex: 2,
      maxChars: 36,
    },
    {
      role: "decor",
      elementId: "kr_card_3",
      type: "shape",
      x: 508,
      y: 180,
      width: 210,
      height: 280,
      zIndex: 1,
    },
    {
      role: "icon",
      elementId: "kr_icon_3",
      type: "icon",
      x: 524,
      y: 200,
      width: 28,
      height: 28,
      zIndex: 3,
      hint: "卡3图标，优先 Success",
    },
    {
      role: "metric",
      elementId: "kr_metric_3",
      type: "text",
      x: 524,
      y: 244,
      width: 178,
      height: 80,
      zIndex: 2,
      maxChars: 10,
    },
    {
      role: "bullet",
      elementId: "kr_label_3",
      type: "text",
      x: 524,
      y: 340,
      width: 178,
      height: 96,
      zIndex: 2,
      maxChars: 36,
    },
    {
      role: "decor",
      elementId: "kr_card_4",
      type: "shape",
      x: 734,
      y: 180,
      width: 210,
      height: 280,
      zIndex: 1,
    },
    {
      role: "icon",
      elementId: "kr_icon_4",
      type: "icon",
      x: 750,
      y: 200,
      width: 28,
      height: 28,
      zIndex: 3,
      hint: "卡4图标，优先 Star",
    },
    {
      role: "metric",
      elementId: "kr_metric_4",
      type: "text",
      x: 750,
      y: 244,
      width: 178,
      height: 80,
      zIndex: 2,
      maxChars: 10,
    },
    {
      role: "bullet",
      elementId: "kr_label_4",
      type: "text",
      x: 750,
      y: 340,
      width: 178,
      height: 96,
      zIndex: 2,
      maxChars: 36,
    },
  ],
};

