import type { LayoutSkeleton } from "../../types";

/** 论证 narrative：two-column / image-text（problem & solution 共用） */

/** 双栏：标题图标 + 左文右图 + 底部要点图标条 */
export const twoColumnLayout: LayoutSkeleton = {
  layoutKey: "two-column",
  name: "双栏图文",
  slots: [
    {
      role: "decor",
      elementId: "tc_accent",
      type: "shape",
      x: 56,
      y: 36,
      width: 48,
      height: 5,
      zIndex: 2,
    },
    {
      role: "icon",
      elementId: "tc_lead_icon",
      type: "icon",
      x: 56,
      y: 52,
      width: 32,
      height: 32,
      zIndex: 3,
      hint: "章节图标，优先 Aiming / Lightning",
    },
    {
      role: "title",
      elementId: "tc_title",
      type: "text",
      x: 100,
      y: 48,
      width: 380,
      height: 56,
      zIndex: 2,
      maxChars: 26,
    },
    {
      role: "body",
      elementId: "tc_body",
      type: "text",
      x: 56,
      y: 120,
      width: 420,
      height: 280,
      zIndex: 2,
      maxChars: 260,
    },
    {
      role: "icon",
      elementId: "tc_chip_1",
      type: "icon",
      x: 56,
      y: 420,
      width: 28,
      height: 28,
      zIndex: 3,
      hint: "要点图标1，优先 CheckOne",
    },
    {
      role: "bullet",
      elementId: "tc_chip_t1",
      type: "text",
      x: 92,
      y: 420,
      width: 100,
      height: 32,
      zIndex: 2,
      maxChars: 8,
      hint: "短标签，如「可验证」",
    },
    {
      role: "icon",
      elementId: "tc_chip_2",
      type: "icon",
      x: 210,
      y: 420,
      width: 28,
      height: 28,
      zIndex: 3,
      hint: "要点图标2，优先 Success",
    },
    {
      role: "bullet",
      elementId: "tc_chip_t2",
      type: "text",
      x: 246,
      y: 420,
      width: 100,
      height: 32,
      zIndex: 2,
      maxChars: 8,
      hint: "短标签",
    },
    {
      role: "icon",
      elementId: "tc_chip_3",
      type: "icon",
      x: 364,
      y: 420,
      width: 28,
      height: 28,
      zIndex: 3,
      hint: "要点图标3，优先 Star",
    },
    {
      role: "bullet",
      elementId: "tc_chip_t3",
      type: "text",
      x: 400,
      y: 420,
      width: 80,
      height: 32,
      zIndex: 2,
      maxChars: 8,
      hint: "短标签",
    },
    {
      role: "image",
      elementId: "tc_image",
      type: "image",
      x: 516,
      y: 48,
      width: 428,
      height: 468,
      zIndex: 1,
      hint: "主插图：与本页论点直接相关的真实场景/产品/人物图，禁止抽象纹理装饰",
    },
  ],
};

/** 左图右文：标题图标 + 文案 + 底部装饰条 */
export const imageTextLayout: LayoutSkeleton = {
  layoutKey: "image-text",
  name: "左图右文",
  slots: [
    {
      role: "image",
      elementId: "it_image",
      type: "image",
      x: 56,
      y: 48,
      width: 428,
      height: 468,
      zIndex: 1,
      hint: "主插图：与本页论点直接相关的真实场景/产品/人物图",
    },
    {
      role: "decor",
      elementId: "it_accent",
      type: "shape",
      x: 516,
      y: 56,
      width: 48,
      height: 5,
      zIndex: 2,
    },
    {
      role: "icon",
      elementId: "it_lead_icon",
      type: "icon",
      x: 516,
      y: 72,
      width: 32,
      height: 32,
      zIndex: 3,
      hint: "章节图标，优先 Lightning / Aiming",
    },
    {
      role: "title",
      elementId: "it_title",
      type: "text",
      x: 560,
      y: 68,
      width: 380,
      height: 56,
      zIndex: 2,
      maxChars: 26,
    },
    {
      role: "body",
      elementId: "it_body",
      type: "text",
      x: 516,
      y: 144,
      width: 428,
      height: 300,
      zIndex: 2,
      maxChars: 260,
    },
    {
      role: "decor",
      elementId: "it_badge",
      type: "shape",
      x: 516,
      y: 470,
      width: 12,
      height: 12,
      zIndex: 2,
      hint: "底部署名点缀，oval",
    },
    {
      role: "icon",
      elementId: "it_foot_icon",
      type: "icon",
      x: 540,
      y: 460,
      width: 28,
      height: 28,
      zIndex: 3,
      hint: "底部辅助图标，优先 CheckOne",
    },
    {
      role: "bullet",
      elementId: "it_foot_text",
      type: "text",
      x: 580,
      y: 460,
      width: 340,
      height: 32,
      zIndex: 2,
      maxChars: 24,
      hint: "一句行动号召或补充说明",
    },
  ],
};
