import type { LayoutSkeleton } from "../../types";

/** 三要点 pillars：three-points / pillars-icons */

/** 三要点：三列对齐网格（列宽 280，间距 24） */
export const threePointsLayout: LayoutSkeleton = {
  layoutKey: "three-points",
  name: "三要点",
  slots: [
    {
      role: "decor",
      elementId: "tp_accent",
      type: "shape",
      x: 56,
      y: 28,
      width: 48,
      height: 5,
      zIndex: 2,
    },
    {
      role: "title",
      elementId: "tp_title",
      type: "text",
      x: 56,
      y: 42,
      width: 888,
      height: 48,
      zIndex: 2,
      maxChars: 32,
    },
    // 列 1 @ x=56
    {
      role: "icon",
      elementId: "tp_icon_1",
      type: "icon",
      x: 56,
      y: 110,
      width: 40,
      height: 40,
      zIndex: 2,
      hint: "要点1图标，优先 Lightning",
    },
    {
      role: "image",
      elementId: "tp_image_1",
      type: "image",
      x: 56,
      y: 164,
      width: 280,
      height: 150,
      zIndex: 1,
      hint: "要点一插图：具体场景",
    },
    {
      role: "bullet",
      elementId: "tp_point_1",
      type: "text",
      x: 56,
      y: 332,
      width: 280,
      height: 190,
      zIndex: 2,
      maxChars: 100,
    },
    // 列 2 @ x=360
    {
      role: "icon",
      elementId: "tp_icon_2",
      type: "icon",
      x: 360,
      y: 110,
      width: 40,
      height: 40,
      zIndex: 2,
      hint: "要点2图标，优先 Aiming",
    },
    {
      role: "image",
      elementId: "tp_image_2",
      type: "image",
      x: 360,
      y: 164,
      width: 280,
      height: 150,
      zIndex: 1,
      hint: "要点二插图：具体场景",
    },
    {
      role: "bullet",
      elementId: "tp_point_2",
      type: "text",
      x: 360,
      y: 332,
      width: 280,
      height: 190,
      zIndex: 2,
      maxChars: 100,
    },
    // 列 3 @ x=664
    {
      role: "icon",
      elementId: "tp_icon_3",
      type: "icon",
      x: 664,
      y: 110,
      width: 40,
      height: 40,
      zIndex: 2,
      hint: "要点3图标，优先 Success",
    },
    {
      role: "image",
      elementId: "tp_image_3",
      type: "image",
      x: 664,
      y: 164,
      width: 280,
      height: 150,
      zIndex: 1,
      hint: "要点三插图：具体场景",
    },
    {
      role: "bullet",
      elementId: "tp_point_3",
      type: "text",
      x: 664,
      y: 332,
      width: 280,
      height: 190,
      zIndex: 2,
      maxChars: 100,
    },
  ],
};


/** 三支柱（图标版）：无插图，图标+标题+正文，更疏朗 */
export const pillarsIconsLayout: LayoutSkeleton = {
  layoutKey: "pillars-icons",
  name: "三要点图标",
  slots: [
    {
      role: "decor",
      elementId: "pi_accent",
      type: "shape",
      x: 56,
      y: 28,
      width: 48,
      height: 5,
      zIndex: 2,
    },
    {
      role: "title",
      elementId: "pi_title",
      type: "text",
      x: 56,
      y: 42,
      width: 888,
      height: 48,
      zIndex: 2,
      maxChars: 32,
    },
    // 列 1
    {
      role: "decor",
      elementId: "pi_card_1",
      type: "shape",
      x: 56,
      y: 120,
      width: 280,
      height: 380,
      zIndex: 1,
    },
    {
      role: "icon",
      elementId: "pi_icon_1",
      type: "icon",
      x: 76,
      y: 152,
      width: 48,
      height: 48,
      zIndex: 2,
      hint: "支柱1图标，优先 Lightning",
    },
    {
      role: "subtitle",
      elementId: "pi_head_1",
      type: "text",
      x: 76,
      y: 220,
      width: 240,
      height: 48,
      zIndex: 2,
      maxChars: 18,
      hint: "要点一标题",
    },
    {
      role: "bullet",
      elementId: "pi_body_1",
      type: "text",
      x: 76,
      y: 280,
      width: 240,
      height: 180,
      zIndex: 2,
      maxChars: 90,
      hint: "问题→方案→结果，含数字",
    },
    // 列 2
    {
      role: "decor",
      elementId: "pi_card_2",
      type: "shape",
      x: 360,
      y: 120,
      width: 280,
      height: 380,
      zIndex: 1,
    },
    {
      role: "icon",
      elementId: "pi_icon_2",
      type: "icon",
      x: 380,
      y: 152,
      width: 48,
      height: 48,
      zIndex: 2,
      hint: "支柱2图标，优先 Aiming",
    },
    {
      role: "subtitle",
      elementId: "pi_head_2",
      type: "text",
      x: 380,
      y: 220,
      width: 240,
      height: 48,
      zIndex: 2,
      maxChars: 18,
    },
    {
      role: "bullet",
      elementId: "pi_body_2",
      type: "text",
      x: 380,
      y: 280,
      width: 240,
      height: 180,
      zIndex: 2,
      maxChars: 90,
    },
    // 列 3
    {
      role: "decor",
      elementId: "pi_card_3",
      type: "shape",
      x: 664,
      y: 120,
      width: 280,
      height: 380,
      zIndex: 1,
    },
    {
      role: "icon",
      elementId: "pi_icon_3",
      type: "icon",
      x: 684,
      y: 152,
      width: 48,
      height: 48,
      zIndex: 2,
      hint: "支柱3图标，优先 Success",
    },
    {
      role: "subtitle",
      elementId: "pi_head_3",
      type: "text",
      x: 684,
      y: 220,
      width: 240,
      height: 48,
      zIndex: 2,
      maxChars: 18,
    },
    {
      role: "bullet",
      elementId: "pi_body_3",
      type: "text",
      x: 684,
      y: 280,
      width: 240,
      height: 180,
      zIndex: 2,
      maxChars: 90,
    },
  ],
};

