import type { LayoutSkeleton } from "../../types";

/** 团队 team：team-cards / team-list */

/** 团队页：三人卡片（头像图 + 姓名 + 简介） */
export const teamCardsLayout: LayoutSkeleton = {
  layoutKey: "team-cards",
  name: "团队卡片",
  slots: [
    {
      role: "decor",
      elementId: "tm_accent",
      type: "shape",
      x: 56,
      y: 28,
      width: 48,
      height: 5,
      zIndex: 3,
    },
    {
      role: "icon",
      elementId: "tm_title_icon",
      type: "icon",
      x: 56,
      y: 46,
      width: 32,
      height: 32,
      zIndex: 4,
      hint: "团队页图标，优先 Peoples",
    },
    {
      role: "title",
      elementId: "tm_title",
      type: "text",
      x: 100,
      y: 44,
      width: 840,
      height: 48,
      zIndex: 3,
      maxChars: 24,
      hint: "团队页标题，如「核心团队」",
    },
    // 成员 1
    {
      role: "decor",
      elementId: "tm_card_1",
      type: "shape",
      x: 56,
      y: 120,
      width: 280,
      height: 380,
      zIndex: 1,
      hint: "成员卡底板",
    },
    {
      role: "image",
      elementId: "tm_photo_1",
      type: "image",
      x: 96,
      y: 148,
      width: 200,
      height: 200,
      zIndex: 2,
      hint: "成员一肖像/半身职业照，干净背景",
    },
    {
      role: "icon",
      elementId: "tm_badge_1",
      type: "icon",
      x: 76,
      y: 360,
      width: 22,
      height: 22,
      zIndex: 3,
      hint: "成员1角标，优先 User",
    },
    {
      role: "subtitle",
      elementId: "tm_name_1",
      type: "text",
      x: 106,
      y: 356,
      width: 210,
      height: 36,
      zIndex: 2,
      maxChars: 16,
      hint: "姓名 · 职位",
    },
    {
      role: "bullet",
      elementId: "tm_bio_1",
      type: "text",
      x: 76,
      y: 400,
      width: 240,
      height: 72,
      zIndex: 2,
      maxChars: 40,
      hint: "一句履历亮点",
    },
    // 成员 2
    {
      role: "decor",
      elementId: "tm_card_2",
      type: "shape",
      x: 360,
      y: 120,
      width: 280,
      height: 380,
      zIndex: 1,
      hint: "成员卡底板",
    },
    {
      role: "image",
      elementId: "tm_photo_2",
      type: "image",
      x: 400,
      y: 148,
      width: 200,
      height: 200,
      zIndex: 2,
      hint: "成员二肖像",
    },
    {
      role: "icon",
      elementId: "tm_badge_2",
      type: "icon",
      x: 380,
      y: 360,
      width: 22,
      height: 22,
      zIndex: 3,
      hint: "成员2角标，优先 Star",
    },
    {
      role: "subtitle",
      elementId: "tm_name_2",
      type: "text",
      x: 410,
      y: 356,
      width: 210,
      height: 36,
      zIndex: 2,
      maxChars: 16,
      hint: "姓名 · 职位",
    },
    {
      role: "bullet",
      elementId: "tm_bio_2",
      type: "text",
      x: 380,
      y: 400,
      width: 240,
      height: 72,
      zIndex: 2,
      maxChars: 40,
      hint: "一句履历亮点",
    },
    // 成员 3
    {
      role: "decor",
      elementId: "tm_card_3",
      type: "shape",
      x: 664,
      y: 120,
      width: 280,
      height: 380,
      zIndex: 1,
      hint: "成员卡底板",
    },
    {
      role: "image",
      elementId: "tm_photo_3",
      type: "image",
      x: 704,
      y: 148,
      width: 200,
      height: 200,
      zIndex: 2,
      hint: "成员三肖像",
    },
    {
      role: "icon",
      elementId: "tm_badge_3",
      type: "icon",
      x: 684,
      y: 360,
      width: 22,
      height: 22,
      zIndex: 3,
      hint: "成员3角标，优先 Lightning",
    },
    {
      role: "subtitle",
      elementId: "tm_name_3",
      type: "text",
      x: 714,
      y: 356,
      width: 210,
      height: 36,
      zIndex: 2,
      maxChars: 16,
      hint: "姓名 · 职位",
    },
    {
      role: "bullet",
      elementId: "tm_bio_3",
      type: "text",
      x: 684,
      y: 400,
      width: 240,
      height: 72,
      zIndex: 2,
      maxChars: 40,
      hint: "一句履历亮点",
    },
  ],
};


/** 团队列表：三人横排精简（小图+姓名+简介） */
export const teamListLayout: LayoutSkeleton = {
  layoutKey: "team-list",
  name: "团队列表",
  slots: [
    {
      role: "decor",
      elementId: "tl2_accent",
      type: "shape",
      x: 56,
      y: 28,
      width: 48,
      height: 5,
      zIndex: 3,
    },
    {
      role: "icon",
      elementId: "tl2_title_icon",
      type: "icon",
      x: 56,
      y: 46,
      width: 32,
      height: 32,
      zIndex: 4,
      hint: "团队页图标，优先 Peoples",
    },
    {
      role: "title",
      elementId: "tl2_title",
      type: "text",
      x: 100,
      y: 44,
      width: 840,
      height: 48,
      zIndex: 3,
      maxChars: 24,
    },
    // row 1
    {
      role: "image",
      elementId: "tl2_photo_1",
      type: "image",
      x: 56,
      y: 120,
      width: 100,
      height: 100,
      zIndex: 2,
      hint: "成员一头像",
    },
    {
      role: "icon",
      elementId: "tl2_badge_1",
      type: "icon",
      x: 180,
      y: 128,
      width: 22,
      height: 22,
      zIndex: 3,
      hint: "成员1角标，优先 User",
    },
    {
      role: "subtitle",
      elementId: "tl2_name_1",
      type: "text",
      x: 212,
      y: 124,
      width: 688,
      height: 36,
      zIndex: 2,
      maxChars: 24,
      hint: "姓名 · 职位",
    },
    {
      role: "bullet",
      elementId: "tl2_bio_1",
      type: "text",
      x: 180,
      y: 168,
      width: 720,
      height: 48,
      zIndex: 2,
      maxChars: 56,
    },
    // row 2
    {
      role: "image",
      elementId: "tl2_photo_2",
      type: "image",
      x: 56,
      y: 248,
      width: 100,
      height: 100,
      zIndex: 2,
      hint: "成员二头像",
    },
    {
      role: "icon",
      elementId: "tl2_badge_2",
      type: "icon",
      x: 180,
      y: 256,
      width: 22,
      height: 22,
      zIndex: 3,
      hint: "成员2角标，优先 Star",
    },
    {
      role: "subtitle",
      elementId: "tl2_name_2",
      type: "text",
      x: 212,
      y: 252,
      width: 688,
      height: 36,
      zIndex: 2,
      maxChars: 24,
    },
    {
      role: "bullet",
      elementId: "tl2_bio_2",
      type: "text",
      x: 180,
      y: 296,
      width: 720,
      height: 48,
      zIndex: 2,
      maxChars: 56,
    },
    // row 3
    {
      role: "image",
      elementId: "tl2_photo_3",
      type: "image",
      x: 56,
      y: 376,
      width: 100,
      height: 100,
      zIndex: 2,
      hint: "成员三头像",
    },
    {
      role: "icon",
      elementId: "tl2_badge_3",
      type: "icon",
      x: 180,
      y: 384,
      width: 22,
      height: 22,
      zIndex: 3,
      hint: "成员3角标，优先 Lightning",
    },
    {
      role: "subtitle",
      elementId: "tl2_name_3",
      type: "text",
      x: 212,
      y: 380,
      width: 688,
      height: 36,
      zIndex: 2,
      maxChars: 24,
    },
    {
      role: "bullet",
      elementId: "tl2_bio_3",
      type: "text",
      x: 180,
      y: 424,
      width: 720,
      height: 48,
      zIndex: 2,
      maxChars: 56,
    },
  ],
};

