import type { LayoutSkeleton } from "../../types";

/** 里程碑 timeline */

/** 里程碑时间线：标题 + 4 个节点（年份 + 事件） */
export const timelineLayout: LayoutSkeleton = {
  layoutKey: "timeline",
  name: "里程碑时间线",
  slots: [
    {
      role: "decor",
      elementId: "tl_accent",
      type: "shape",
      x: 56,
      y: 28,
      width: 48,
      height: 5,
      zIndex: 3,
    },
    {
      role: "icon",
      elementId: "tl_icon",
      type: "icon",
      x: 56,
      y: 40,
      width: 32,
      height: 32,
      zIndex: 4,
      hint: "里程碑图标，优先 Lightning",
    },
    {
      role: "title",
      elementId: "tl_title",
      type: "text",
      x: 100,
      y: 38,
      width: 840,
      height: 48,
      zIndex: 3,
      maxChars: 28,
      hint: "如「发展里程碑」",
    },
    // 轴线
    {
      role: "decor",
      elementId: "tl_axis",
      type: "shape",
      x: 80,
      y: 280,
      width: 840,
      height: 4,
      zIndex: 1,
      hint: "时间轴线",
    },
    // 节点 1
    {
      role: "decor",
      elementId: "tl_dot_1",
      type: "shape",
      x: 120,
      y: 268,
      width: 28,
      height: 28,
      zIndex: 2,
      hint: "节点圆点，优先 oval",
    },
    {
      role: "icon",
      elementId: "tl_node_icon_1",
      type: "icon",
      x: 122,
      y: 220,
      width: 24,
      height: 24,
      zIndex: 3,
      hint: "节点1图标，优先 Star",
    },
    {
      role: "metric",
      elementId: "tl_year_1",
      type: "text",
      x: 72,
      y: 150,
      width: 140,
      height: 48,
      zIndex: 2,
      maxChars: 8,
      hint: "年份/季度，如 2023",
    },
    {
      role: "bullet",
      elementId: "tl_event_1",
      type: "text",
      x: 56,
      y: 320,
      width: 200,
      height: 140,
      zIndex: 2,
      maxChars: 48,
      hint: "该节点关键事件",
    },
    // 节点 2
    {
      role: "decor",
      elementId: "tl_dot_2",
      type: "shape",
      x: 364,
      y: 268,
      width: 28,
      height: 28,
      zIndex: 2,
      hint: "节点圆点",
    },
    {
      role: "icon",
      elementId: "tl_node_icon_2",
      type: "icon",
      x: 366,
      y: 220,
      width: 24,
      height: 24,
      zIndex: 3,
      hint: "节点2图标，优先 Aiming",
    },
    {
      role: "metric",
      elementId: "tl_year_2",
      type: "text",
      x: 316,
      y: 150,
      width: 140,
      height: 48,
      zIndex: 2,
      maxChars: 8,
      hint: "年份/季度",
    },
    {
      role: "bullet",
      elementId: "tl_event_2",
      type: "text",
      x: 300,
      y: 320,
      width: 200,
      height: 140,
      zIndex: 2,
      maxChars: 48,
      hint: "该节点关键事件",
    },
    // 节点 3
    {
      role: "decor",
      elementId: "tl_dot_3",
      type: "shape",
      x: 608,
      y: 268,
      width: 28,
      height: 28,
      zIndex: 2,
      hint: "节点圆点",
    },
    {
      role: "icon",
      elementId: "tl_node_icon_3",
      type: "icon",
      x: 610,
      y: 220,
      width: 24,
      height: 24,
      zIndex: 3,
      hint: "节点3图标，优先 Success",
    },
    {
      role: "metric",
      elementId: "tl_year_3",
      type: "text",
      x: 560,
      y: 150,
      width: 140,
      height: 48,
      zIndex: 2,
      maxChars: 8,
      hint: "年份/季度",
    },
    {
      role: "bullet",
      elementId: "tl_event_3",
      type: "text",
      x: 544,
      y: 320,
      width: 200,
      height: 140,
      zIndex: 2,
      maxChars: 48,
      hint: "该节点关键事件",
    },
    // 节点 4
    {
      role: "decor",
      elementId: "tl_dot_4",
      type: "shape",
      x: 852,
      y: 268,
      width: 28,
      height: 28,
      zIndex: 2,
      hint: "节点圆点",
    },
    {
      role: "icon",
      elementId: "tl_node_icon_4",
      type: "icon",
      x: 854,
      y: 220,
      width: 24,
      height: 24,
      zIndex: 3,
      hint: "节点4图标，优先 Lightning",
    },
    {
      role: "metric",
      elementId: "tl_year_4",
      type: "text",
      x: 804,
      y: 150,
      width: 140,
      height: 48,
      zIndex: 2,
      maxChars: 8,
      hint: "年份/季度",
    },
    {
      role: "bullet",
      elementId: "tl_event_4",
      type: "text",
      x: 788,
      y: 320,
      width: 200,
      height: 140,
      zIndex: 2,
      maxChars: 48,
      hint: "该节点关键事件",
    },
  ],
};

