/**
 * Safe hero variants: each keeps readable text on solid surfaces while changing
 * first-page posture by archetype.
 */

/** Product launch: left editorial copy, right framed product media object. */
export const HERO_PRODUCT_SHOWCASE = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;font-family:{{fontTitle}},serif;">
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="5" style="position:absolute;left:0;top:0;width:100%;height:8px;background:{{secondary}};z-index:5;"></div>
  <div data-element="1" data-type="shape" data-shape-type="roundedRect" data-fill="{{cardFill}}" data-border data-border-color="{{hairline}}" data-border-width="1" data-border-radius="28" data-z-index="8" style="position:absolute;right:64px;top:62px;width:374px;height:438px;background:{{cardFill}};border:1px solid {{hairline}};border-radius:28px;z-index:8;"></div>
  <div data-element="1" data-type="image" data-asset-key="{{bgImageKey}}" data-image-prompt="{{bgImagePrompt}}" data-image-kind="photo" data-border-radius="22" data-z-index="12" style="position:absolute;right:84px;top:82px;width:334px;height:330px;border-radius:22px;z-index:12;overflow:hidden;"></div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{primary}}" data-z-index="14" style="position:absolute;right:84px;top:434px;width:118px;height:4px;background:{{primary}};z-index:14;"></div>
  <div data-element="1" data-type="text" data-font-size="10" data-font-family="{{fontBody}}" data-color="{{accentText}}" data-line-height="1.3" data-placement="left-top" data-z-index="30" translate="no" style="position:absolute;left:72px;top:68px;width:380px;font-size:10px;font-family:{{fontBody}},sans-serif;letter-spacing:0.22em;color:{{accentText}};line-height:1.3;z-index:30;">{{footer}}</div>
  <div data-element="1" data-type="text" data-font-size="52" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.08" data-placement="left-top" data-bold data-z-index="31" style="position:absolute;left:72px;top:154px;width:440px;font-size:52px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.08;z-index:31;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div data-element="1" data-type="text" data-font-size="15" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.6" data-placement="left-top" data-z-index="32" style="position:absolute;left:72px;bottom:70px;width:430px;font-size:15px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.6;z-index:32;text-wrap:pretty;overflow-wrap:anywhere;">{{subtitle}}</div>
</section>`;

/** Data / pitch: oversized typographic monument, no image dependency. */
export const HERO_DATA_MONUMENT = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{primary}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{primary}};box-sizing:border-box;font-family:{{fontTitle}},serif;">
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="6" style="position:absolute;left:0;top:0;width:100%;height:5px;background:{{secondary}};z-index:6;"></div>
  <div data-element="1" data-type="text" data-font-size="10" data-font-family="{{fontBody}}" data-color="{{accentOnPrimary}}" data-line-height="1.3" data-placement="left-top" data-z-index="30" translate="no" style="position:absolute;left:58px;top:50px;width:560px;font-size:10px;font-family:{{fontBody}},sans-serif;letter-spacing:0.26em;color:{{accentOnPrimary}};line-height:1.3;z-index:30;">{{footer}}</div>
  <div data-element="1" data-type="text" data-font-size="76" data-font-family="{{fontTitle}}" data-color="{{textOnDark}}" data-line-height="0.98" data-placement="left-center" data-bold data-z-index="31" style="position:absolute;left:58px;top:130px;width:770px;font-size:76px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnDark}};line-height:0.98;z-index:31;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="7" style="position:absolute;right:74px;top:116px;width:4px;height:286px;background:{{secondary}};z-index:7;"></div>
  <div data-element="1" data-type="text" data-font-size="15" data-font-family="{{fontBody}}" data-color="{{textOnDark}}" data-line-height="1.6" data-placement="left-top" data-z-index="32" style="position:absolute;left:62px;bottom:58px;width:620px;font-size:15px;font-family:{{fontBody}},sans-serif;color:{{textOnDark}};line-height:1.6;z-index:32;text-wrap:pretty;overflow-wrap:anywhere;">{{subtitle}}</div>
</section>`;

/** Consulting / report: left spine and right annotation panel. */
export const HERO_REPORT_SPINE = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;font-family:{{fontTitle}},serif;">
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{primary}}" data-z-index="5" style="position:absolute;left:0;top:0;width:118px;height:100%;background:{{primary}};z-index:5;"></div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="6" style="position:absolute;left:118px;top:0;width:5px;height:100%;background:{{secondary}};z-index:6;"></div>
  <div data-element="1" data-type="text" data-font-size="10" data-font-family="{{fontBody}}" data-color="{{accentOnPrimary}}" data-line-height="1.3" data-placement="left-top" data-z-index="30" translate="no" style="position:absolute;left:34px;top:56px;width:58px;font-size:10px;font-family:{{fontBody}},sans-serif;letter-spacing:0.18em;color:{{accentOnPrimary}};line-height:1.3;z-index:30;overflow-wrap:anywhere;">{{footer}}</div>
  <div data-element="1" data-type="text" data-font-size="54" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.08" data-placement="left-top" data-bold data-z-index="31" style="position:absolute;left:174px;top:122px;width:540px;font-size:54px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.08;z-index:31;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div data-element="1" data-type="shape" data-shape-type="roundedRect" data-fill="{{cardFill}}" data-border data-border-color="{{hairline}}" data-border-width="1" data-border-radius="20" data-z-index="8" style="position:absolute;right:58px;top:146px;width:220px;height:252px;background:{{cardFill}};border:1px solid {{hairline}};border-radius:20px;z-index:8;"></div>
  <div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.65" data-placement="left-top" data-z-index="32" style="position:absolute;right:82px;top:178px;width:172px;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.65;z-index:32;text-wrap:pretty;overflow-wrap:anywhere;">{{subtitle}}</div>
</section>`;

/** Stage / gala: centered marquee on dark solid stage, no text over image. */
export const HERO_STAGE_MARQUEE = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{primary}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{primary}};box-sizing:border-box;font-family:{{fontTitle}},serif;">
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="5" style="position:absolute;left:0;top:70px;width:100%;height:2px;background:{{secondary}};z-index:5;"></div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="5" style="position:absolute;left:0;bottom:70px;width:100%;height:2px;background:{{secondary}};z-index:5;"></div>
  <div data-element="1" data-type="text" data-font-size="10" data-font-family="{{fontBody}}" data-color="{{accentOnPrimary}}" data-line-height="1.3" data-placement="center-top" data-z-index="30" translate="no" style="position:absolute;left:190px;top:105px;width:620px;font-size:10px;font-family:{{fontBody}},sans-serif;letter-spacing:0.28em;color:{{accentOnPrimary}};line-height:1.3;text-align:center;z-index:30;">{{footer}}</div>
  <div data-element="1" data-type="text" data-font-size="58" data-font-family="{{fontTitle}}" data-color="{{textOnDark}}" data-line-height="1.08" data-placement="center-center" data-bold data-z-index="31" style="position:absolute;left:120px;top:178px;width:760px;font-size:58px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnDark}};line-height:1.08;text-align:center;z-index:31;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div data-element="1" data-type="shape" data-shape-type="roundedRect" data-fill="{{scrim}}" data-border data-border-color="{{secondary}}" data-border-width="1" data-border-radius="999" data-z-index="8" style="position:absolute;left:230px;bottom:106px;width:540px;height:58px;background:{{scrim}};border:1px solid {{secondary}};border-radius:999px;z-index:8;"></div>
  <div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{textOnDark}}" data-line-height="1.45" data-placement="center-center" data-z-index="32" style="position:absolute;left:260px;bottom:118px;width:480px;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{textOnDark}};line-height:1.45;text-align:center;z-index:32;overflow:hidden;overflow-wrap:anywhere;">{{subtitle}}</div>
</section>`;
