/**
 * 封面族 — frontend-design + web-design-guidelines
 * 节奏：竖轨 5×268 @ (64,156)；边距 56；标题 balance；英文 eyebrow translate=no。
 */

/** Signature: 左侧黄铜竖轨锚定标题基线 */
export const HERO_RAIL = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" data-bg-image-key="{{bgImageKey}}" data-bg-image-prompt="{{bgImagePrompt}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;font-family:{{fontTitle}},sans-serif;">
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="8" style="position:absolute;left:64px;top:156px;width:5px;height:268px;background:{{secondary}};z-index:8;"></div>
  <div data-element="1" data-type="text" data-font-size="11" data-font-family="{{fontBody}}" data-color="{{secondary}}" data-line-height="1.3" data-placement="left-top" data-z-index="30" translate="no" style="position:absolute;left:92px;top:52px;width:480px;font-size:11px;font-family:{{fontBody}},sans-serif;letter-spacing:0.18em;color:{{secondary}};line-height:1.3;z-index:30;">{{footer}}</div>
  <div data-element="1" data-type="text" data-font-size="48" data-font-family="{{fontTitle}}" data-color="{{textOnDark}}" data-line-height="1.12" data-placement="left-bottom" data-bold data-z-index="31" style="position:absolute;left:92px;bottom:150px;width:760px;font-size:48px;font-family:{{fontTitle}},sans-serif;font-weight:700;color:{{textOnDark}};line-height:1.12;z-index:31;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div data-element="1" data-type="text" data-font-size="16" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="32" style="position:absolute;left:92px;bottom:68px;width:520px;font-size:16px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:32;text-wrap:pretty;overflow-wrap:anywhere;">{{subtitle}}</div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="5" style="position:absolute;left:0;bottom:0;width:100%;height:3px;background:{{secondary}};z-index:5;"></div>
</section>`;

/** Signature: 右三分之一实底强调栏，标题只占左墨区 */
export const HERO_SPLIT = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" data-bg-image-key="{{bgImageKey}}" data-bg-image-prompt="{{bgImagePrompt}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;font-family:{{fontTitle}},sans-serif;">
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="5" style="position:absolute;right:0;top:0;width:340px;height:100%;background:{{secondary}};z-index:5;"></div>
  <div data-element="1" data-type="text" data-font-size="11" data-font-family="{{fontBody}}" data-color="{{secondary}}" data-line-height="1.3" data-placement="left-top" data-z-index="30" translate="no" style="position:absolute;left:56px;top:48px;width:420px;font-size:11px;font-family:{{fontBody}},sans-serif;letter-spacing:0.18em;color:{{secondary}};line-height:1.3;z-index:30;">{{footer}}</div>
  <div data-element="1" data-type="text" data-font-size="44" data-font-family="{{fontTitle}}" data-color="{{textOnDark}}" data-line-height="1.15" data-placement="left-center" data-bold data-z-index="31" style="position:absolute;left:56px;top:190px;width:520px;font-size:44px;font-family:{{fontTitle}},sans-serif;font-weight:700;color:{{textOnDark}};line-height:1.15;z-index:31;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div data-element="1" data-type="text" data-font-size="15" data-font-family="{{fontBody}}" data-color="{{primary}}" data-line-height="1.65" data-placement="left-top" data-z-index="32" style="position:absolute;right:40px;top:210px;width:260px;font-size:15px;font-family:{{fontBody}},sans-serif;color:{{primary}};line-height:1.65;z-index:32;text-wrap:pretty;overflow-wrap:anywhere;">{{subtitle}}</div>
</section>`;

/** Signature: 超大标题贴底，画面几乎只剩字 */
export const HERO_TYPE = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" data-bg-image-key="{{bgImageKey}}" data-bg-image-prompt="{{bgImagePrompt}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;font-family:{{fontTitle}},sans-serif;">
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="5" style="position:absolute;left:0;top:0;width:100%;height:3px;background:{{secondary}};z-index:5;"></div>
  <div data-element="1" data-type="text" data-font-size="11" data-font-family="{{fontBody}}" data-color="{{secondary}}" data-line-height="1.3" data-placement="left-top" data-z-index="30" translate="no" style="position:absolute;left:48px;top:40px;width:560px;font-size:11px;font-family:{{fontBody}},sans-serif;letter-spacing:0.18em;color:{{secondary}};line-height:1.3;z-index:30;">{{footer}}</div>
  <div data-element="1" data-type="text" data-font-size="64" data-font-family="{{fontTitle}}" data-color="{{textOnDark}}" data-line-height="1.05" data-placement="left-bottom" data-bold data-z-index="31" style="position:absolute;left:48px;bottom:108px;width:904px;font-size:64px;font-family:{{fontTitle}},sans-serif;font-weight:700;color:{{textOnDark}};line-height:1.05;z-index:31;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div data-element="1" data-type="text" data-font-size="15" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="32" style="position:absolute;left:48px;bottom:48px;width:680px;font-size:15px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:32;text-wrap:pretty;overflow-wrap:anywhere;">{{subtitle}}</div>
</section>`;

/** Signature: 左边条脊线 + 右侧窄栏副文（宣言版式） */
export const MANIFESTO_COVER = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" data-bg-image-key="{{bgImageKey}}" data-bg-image-prompt="{{bgImagePrompt}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;font-family:{{fontTitle}},sans-serif;">
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="5" style="position:absolute;left:0;top:0;width:14px;height:100%;background:{{secondary}};z-index:5;"></div>
  <div data-element="1" data-type="text" data-font-size="11" data-font-family="{{fontBody}}" data-color="{{secondary}}" data-line-height="1.3" data-placement="left-top" data-z-index="30" translate="no" style="position:absolute;left:56px;top:48px;width:320px;font-size:11px;font-family:{{fontBody}},sans-serif;letter-spacing:0.18em;color:{{secondary}};line-height:1.3;z-index:30;">{{footer}}</div>
  <div data-element="1" data-type="text" data-font-size="48" data-font-family="{{fontTitle}}" data-color="{{textOnDark}}" data-line-height="1.12" data-placement="left-center" data-bold data-z-index="31" style="position:absolute;left:56px;top:168px;width:600px;font-size:48px;font-family:{{fontTitle}},sans-serif;font-weight:700;color:{{textOnDark}};line-height:1.12;z-index:31;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{divider}}" data-z-index="8" style="position:absolute;right:280px;top:168px;width:1px;height:200px;background:{{divider}};z-index:8;"></div>
  <div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.7" data-placement="left-top" data-z-index="32" style="position:absolute;right:48px;top:168px;width:210px;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.7;z-index:32;text-wrap:pretty;overflow-wrap:anywhere;">{{subtitle}}</div>
</section>`;
