/**
 * 封面族 — 拉开字阶：eyebrow 更小更疏，标题更大；标题用衬线气质（fontTitle）。
 */

/** Signature: 左侧黄铜竖轨锚定标题基线 */
export const HERO_RAIL = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" data-bg-image-key="{{bgImageKey}}" data-bg-image-prompt="{{bgImagePrompt}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;font-family:{{fontTitle}},serif;">
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="8" style="position:absolute;left:64px;top:156px;width:5px;height:268px;background:{{secondary}};z-index:8;"></div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{scrim}}" data-z-index="25" style="position:absolute;left:80px;top:36px;width:420px;height:36px;background:{{scrim}};z-index:25;"></div>
  <div data-element="1" data-type="text" data-font-size="10" data-font-family="{{fontBody}}" data-color="{{eyebrow}}" data-line-height="1.3" data-placement="left-top" data-z-index="30" translate="no" style="position:absolute;left:92px;top:48px;width:480px;font-size:10px;font-family:{{fontBody}},sans-serif;letter-spacing:0.28em;color:{{eyebrow}};line-height:1.3;z-index:30;">{{footer}}</div>
  <div data-element="1" data-type="text" data-font-size="56" data-font-family="{{fontTitle}}" data-color="{{textOnDark}}" data-line-height="1.08" data-placement="left-bottom" data-bold data-z-index="31" style="position:absolute;left:92px;bottom:142px;width:760px;font-size:56px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnDark}};line-height:1.08;z-index:31;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div data-element="1" data-type="text" data-font-size="15" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.6" data-placement="left-top" data-z-index="32" style="position:absolute;left:92px;bottom:64px;width:520px;font-size:15px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.6;z-index:32;text-wrap:pretty;overflow-wrap:anywhere;">{{subtitle}}</div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="5" style="position:absolute;left:0;bottom:0;width:100%;height:3px;background:{{secondary}};z-index:5;"></div>
</section>`;

/** Signature: 右三分之一实底强调栏，标题只占左墨区 */
export const HERO_SPLIT = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" data-bg-image-key="{{bgImageKey}}" data-bg-image-prompt="{{bgImagePrompt}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;font-family:{{fontTitle}},serif;">
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="5" style="position:absolute;right:0;top:0;width:340px;height:100%;background:{{secondary}};z-index:5;"></div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{scrim}}" data-z-index="25" style="position:absolute;left:44px;top:32px;width:380px;height:36px;background:{{scrim}};z-index:25;"></div>
  <div data-element="1" data-type="text" data-font-size="10" data-font-family="{{fontBody}}" data-color="{{eyebrow}}" data-line-height="1.3" data-placement="left-top" data-z-index="30" translate="no" style="position:absolute;left:56px;top:44px;width:420px;font-size:10px;font-family:{{fontBody}},sans-serif;letter-spacing:0.28em;color:{{eyebrow}};line-height:1.3;z-index:30;">{{footer}}</div>
  <div data-element="1" data-type="text" data-font-size="52" data-font-family="{{fontTitle}}" data-color="{{textOnDark}}" data-line-height="1.1" data-placement="left-center" data-bold data-z-index="31" style="position:absolute;left:56px;top:178px;width:520px;font-size:52px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnDark}};line-height:1.1;z-index:31;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div data-element="1" data-type="text" data-font-size="15" data-font-family="{{fontBody}}" data-color="{{primaryText}}" data-line-height="1.65" data-placement="left-top" data-z-index="32" style="position:absolute;right:40px;top:210px;width:260px;font-size:15px;font-family:{{fontBody}},sans-serif;color:{{primaryText}};line-height:1.65;z-index:32;text-wrap:pretty;overflow-wrap:anywhere;">{{subtitle}}</div>
</section>`;

/** Signature: 超大标题贴底，画面几乎只剩字 */
export const HERO_TYPE = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" data-bg-image-key="{{bgImageKey}}" data-bg-image-prompt="{{bgImagePrompt}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;font-family:{{fontTitle}},serif;">
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="5" style="position:absolute;left:0;top:0;width:100%;height:3px;background:{{secondary}};z-index:5;"></div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{scrim}}" data-z-index="25" style="position:absolute;left:36px;top:24px;width:480px;height:36px;background:{{scrim}};z-index:25;"></div>
  <div data-element="1" data-type="text" data-font-size="10" data-font-family="{{fontBody}}" data-color="{{eyebrow}}" data-line-height="1.3" data-placement="left-top" data-z-index="30" translate="no" style="position:absolute;left:48px;top:36px;width:560px;font-size:10px;font-family:{{fontBody}},sans-serif;letter-spacing:0.28em;color:{{eyebrow}};line-height:1.3;z-index:30;">{{footer}}</div>
  <div data-element="1" data-type="text" data-font-size="72" data-font-family="{{fontTitle}}" data-color="{{textOnDark}}" data-line-height="1.02" data-placement="left-bottom" data-bold data-z-index="31" style="position:absolute;left:48px;bottom:100px;width:904px;font-size:72px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnDark}};line-height:1.02;z-index:31;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div data-element="1" data-type="text" data-font-size="15" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.6" data-placement="left-top" data-z-index="32" style="position:absolute;left:48px;bottom:44px;width:680px;font-size:15px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.6;z-index:32;text-wrap:pretty;overflow-wrap:anywhere;">{{subtitle}}</div>
</section>`;

/** Signature: 左边条脊线 + 右侧窄栏副文（宣言版式） */
export const MANIFESTO_COVER = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" data-bg-image-key="{{bgImageKey}}" data-bg-image-prompt="{{bgImagePrompt}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;font-family:{{fontTitle}},serif;">
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="5" style="position:absolute;left:0;top:0;width:14px;height:100%;background:{{secondary}};z-index:5;"></div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{scrim}}" data-z-index="25" style="position:absolute;left:44px;top:32px;width:300px;height:36px;background:{{scrim}};z-index:25;"></div>
  <div data-element="1" data-type="text" data-font-size="10" data-font-family="{{fontBody}}" data-color="{{eyebrow}}" data-line-height="1.3" data-placement="left-top" data-z-index="30" translate="no" style="position:absolute;left:56px;top:44px;width:320px;font-size:10px;font-family:{{fontBody}},sans-serif;letter-spacing:0.28em;color:{{eyebrow}};line-height:1.3;z-index:30;">{{footer}}</div>
  <div data-element="1" data-type="text" data-font-size="56" data-font-family="{{fontTitle}}" data-color="{{textOnDark}}" data-line-height="1.08" data-placement="left-center" data-bold data-z-index="31" style="position:absolute;left:56px;top:160px;width:600px;font-size:56px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnDark}};line-height:1.08;z-index:31;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{divider}}" data-z-index="8" style="position:absolute;right:280px;top:168px;width:1px;height:200px;background:{{divider}};z-index:8;"></div>
  <div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.7" data-placement="left-top" data-z-index="32" style="position:absolute;right:48px;top:168px;width:210px;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.7;z-index:32;text-wrap:pretty;overflow-wrap:anywhere;">{{subtitle}}</div>
</section>`;
