/**
 * Wave-4 — 贵价签名 + 边距变化（非对称 / 敢空）
 * 硬约束：无 transform；text 无 padding；shape 作色块；data-* ↔ CSS。
 */

/** Signature: 左半幅实色板托住巨型标题；右侧媒体槽（双平面） */
export const HERO_SLAB = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;font-family:{{fontTitle}},serif;">
  <div data-element="1" data-type="image" data-asset-key="{{bgImageKey}}" data-image-prompt="{{bgImagePrompt}}" data-image-kind="photo" data-border-radius="0" data-z-index="4" style="position:absolute;left:460px;top:0;width:540px;height:100%;z-index:4;overflow:hidden;"></div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{primary}}" data-z-index="10" style="position:absolute;left:0;top:0;width:460px;height:100%;background:{{primary}};z-index:10;"></div>
  <div data-element="1" data-type="text" data-font-size="10" data-font-family="{{fontBody}}" data-color="{{eyebrow}}" data-line-height="1.3" data-placement="left-top" data-z-index="30" translate="no" style="position:absolute;left:56px;top:40px;width:340px;font-size:10px;font-family:{{fontBody}},sans-serif;letter-spacing:0.28em;color:{{eyebrow}};line-height:1.3;z-index:30;">{{footer}}</div>
  <div data-element="1" data-type="text" data-font-size="58" data-font-family="{{fontTitle}}" data-color="{{textOnDark}}" data-line-height="1.06" data-placement="left-bottom" data-bold data-z-index="31" style="position:absolute;left:56px;bottom:120px;width:360px;font-size:58px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnDark}};line-height:1.06;z-index:31;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div data-element="1" data-type="text" data-font-size="15" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="32" style="position:absolute;left:56px;bottom:52px;width:360px;font-size:15px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:32;text-wrap:pretty;overflow-wrap:anywhere;">{{subtitle}}</div>
</section>`;

/** Signature: 单主指标纪念碑，整页几乎只剩一个数字 */
export const METRICS_MONUMENT = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;font-family:{{fontTitle}},serif;">
  <div data-element="1" data-type="text" data-font-size="12" data-font-family="{{fontBody}}" data-color="{{accentText}}" data-line-height="1.3" data-placement="left-top" data-z-index="28" translate="no" style="position:absolute;left:72px;top:56px;width:400px;font-size:12px;font-family:{{fontBody}},sans-serif;letter-spacing:0.22em;color:{{accentText}};line-height:1.3;z-index:28;">{{title}}</div>
  <div data-element="1" data-type="text" data-font-size="140" data-font-family="{{fontNumeric}}" data-color="{{primaryText}}" data-line-height="0.9" data-placement="left-center" data-bold data-z-index="30" style="position:absolute;left:72px;top:160px;width:700px;font-size:140px;font-family:{{fontNumeric}},serif;font-weight:700;color:{{primaryText}};line-height:0.9;z-index:30;font-variant-numeric:tabular-nums;overflow-wrap:anywhere;">{{m1.value}}</div>
  <div data-element="1" data-type="text" data-font-size="18" data-font-family="{{fontBody}}" data-color="{{textOnLight}}" data-line-height="1.45" data-placement="left-top" data-z-index="31" style="position:absolute;left:72px;bottom:120px;width:520px;font-size:18px;font-family:{{fontBody}},sans-serif;color:{{textOnLight}};line-height:1.45;z-index:31;overflow-wrap:anywhere;">{{m1.label}}</div>
  <div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.5" data-placement="left-top" data-z-index="32" style="position:absolute;left:72px;bottom:56px;width:700px;font-size:13px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.5;z-index:32;text-wrap:pretty;overflow-wrap:anywhere;">{{footer}}</div>
</section>`;

/** Signature: 巨幅引语广告牌，极端留白 */
export const BREATH_BILLBOARD = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;font-family:{{fontTitle}},serif;">
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="8" style="position:absolute;left:80px;top:120px;width:48px;height:3px;background:{{secondary}};z-index:8;"></div>
  <div data-element="1" data-type="text" data-font-size="42" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.25" data-placement="left-center" data-bold data-z-index="30" style="position:absolute;left:80px;top:160px;width:760px;font-size:42px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.25;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{quote}}</div>
  <div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.5" data-placement="left-top" data-z-index="31" style="position:absolute;left:80px;bottom:88px;width:480px;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.5;z-index:31;overflow-wrap:anywhere;">{{attribution}}</div>
</section>`;

/** Signature: 疏边距证据广场（padding 32×72） */
export const EVIDENCE_PLAZA = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;padding:32px 72px;font-family:{{fontTitle}},serif;">
  <div data-element="1" data-type="text" data-font-size="28" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.15" data-placement="left-top" data-bold data-z-index="30" style="width:640px;font-size:28px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.15;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div data-element="1" data-type="shape" data-shape-type="roundedRect" data-fill="{{background}}" data-border data-border-color="{{hairline}}" data-border-width="1" data-border-radius="14" data-z-index="12" style="position:absolute;right:72px;top:36px;width:220px;height:98px;background:{{background}};border:1px solid {{hairline}};border-radius:14px;z-index:12;"></div>
  <div data-element="1" data-type="text" data-font-size="12" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.45" data-placement="right-top" data-z-index="31" style="position:absolute;right:88px;top:52px;width:188px;height:70px;font-size:12px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.45;z-index:31;text-align:left;overflow:hidden;overflow-wrap:anywhere;">{{caption}}</div>
  <div data-element="1" data-type="image" data-asset-key="{{imageKey}}" data-image-prompt="{{imagePrompt}}" data-image-kind="photo" data-border-radius="0" data-z-index="10" style="width:856px;height:300px;margin-top:24px;z-index:10;overflow:hidden;"></div>
  <div style="display:flex;gap:32px;margin-top:20px;width:856px;">
    <div style="flex:1;min-width:0;"><div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontBody}}" data-color="{{textOnLight}}" data-line-height="1.5" data-placement="left-top" data-z-index="32" style="width:100%;font-size:13px;font-family:{{fontBody}},sans-serif;color:{{textOnLight}};line-height:1.5;z-index:32;overflow-wrap:anywhere;">{{b1}}</div></div>
    <div style="flex:1;min-width:0;"><div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontBody}}" data-color="{{textOnLight}}" data-line-height="1.5" data-placement="left-top" data-z-index="33" style="width:100%;font-size:13px;font-family:{{fontBody}},sans-serif;color:{{textOnLight}};line-height:1.5;z-index:33;overflow-wrap:anywhere;">{{b2}}</div></div>
    <div style="flex:1;min-width:0;"><div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontBody}}" data-color="{{textOnLight}}" data-line-height="1.5" data-placement="left-top" data-z-index="34" style="width:100%;font-size:13px;font-family:{{fontBody}},sans-serif;color:{{textOnLight}};line-height:1.5;z-index:34;overflow-wrap:anywhere;">{{b3}}</div></div>
  </div>
</section>`;

/** Signature: 宽松边距三要点（padding 56×80） */
export const PILLARS_LOOSE = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;padding:56px 80px;font-family:{{fontTitle}},serif;">
  <div data-element="1" data-type="text" data-font-size="11" data-font-family="{{fontBody}}" data-color="{{accentText}}" data-line-height="1.3" data-placement="left-top" data-z-index="28" translate="no" style="width:200px;font-size:11px;font-family:{{fontBody}},sans-serif;letter-spacing:0.22em;color:{{accentText}};line-height:1.3;z-index:28;">PILLARS</div>
  <div data-element="1" data-type="text" data-font-size="34" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.15" data-placement="left-top" data-bold data-z-index="30" style="width:720px;margin-top:12px;font-size:34px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.15;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div style="display:flex;gap:40px;margin-top:48px;width:840px;">
    <div style="flex:1;min-width:0;">
      <div data-element="1" data-type="icon" aria-hidden="true" data-icon-name="{{p1.iconName}}" data-icon-theme="outline" data-fill="{{primary}}" data-stroke-width="3" data-z-index="29" style="width:28px;height:28px;z-index:29;"></div>
      <div data-element="1" data-type="text" data-font-size="18" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.3" data-placement="left-top" data-bold data-z-index="30" style="width:100%;margin-top:16px;font-size:18px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.3;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{p1.title}}</div>
      <div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="31" style="width:100%;margin-top:10px;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:31;overflow-wrap:anywhere;">{{p1.body}}</div>
    </div>
    <div style="flex:1;min-width:0;">
      <div data-element="1" data-type="icon" aria-hidden="true" data-icon-name="{{p2.iconName}}" data-icon-theme="outline" data-fill="{{primary}}" data-stroke-width="3" data-z-index="29" style="width:28px;height:28px;z-index:29;"></div>
      <div data-element="1" data-type="text" data-font-size="18" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.3" data-placement="left-top" data-bold data-z-index="30" style="width:100%;margin-top:16px;font-size:18px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.3;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{p2.title}}</div>
      <div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="31" style="width:100%;margin-top:10px;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:31;overflow-wrap:anywhere;">{{p2.body}}</div>
    </div>
    <div style="flex:1;min-width:0;">
      <div data-element="1" data-type="icon" aria-hidden="true" data-icon-name="{{p3.iconName}}" data-icon-theme="outline" data-fill="{{primary}}" data-stroke-width="3" data-z-index="29" style="width:28px;height:28px;z-index:29;"></div>
      <div data-element="1" data-type="text" data-font-size="18" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.3" data-placement="left-top" data-bold data-z-index="30" style="width:100%;margin-top:16px;font-size:18px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.3;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{p3.title}}</div>
      <div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="31" style="width:100%;margin-top:10px;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:31;overflow-wrap:anywhere;">{{p3.body}}</div>
    </div>
  </div>
</section>`;

/** Signature: 紧边距问题页（padding 28×40），信息更满作节奏对比 */
export const PROBLEM_TIGHT = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;padding:28px 40px;font-family:{{fontTitle}},serif;">
  <div data-element="1" data-type="text" data-font-size="11" data-font-family="{{fontBody}}" data-color="{{accentText}}" data-line-height="1.3" data-placement="left-top" data-z-index="28" translate="no" style="width:200px;font-size:11px;font-family:{{fontBody}},sans-serif;letter-spacing:0.2em;color:{{accentText}};line-height:1.3;z-index:28;">THE PROBLEM</div>
  <div data-element="1" data-type="text" data-font-size="32" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.15" data-placement="left-top" data-bold data-z-index="30" style="width:920px;margin-top:8px;font-size:32px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.15;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div data-element="1" data-type="text" data-font-size="15" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.65" data-placement="left-top" data-z-index="31" style="width:920px;margin-top:16px;font-size:15px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.65;z-index:31;text-wrap:pretty;overflow-wrap:anywhere;">{{body}}</div>
  <div style="display:flex;gap:20px;margin-top:28px;width:920px;">
    <div style="flex:1;min-width:0;"><div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="9" style="width:28px;height:3px;margin-bottom:10px;background:{{secondary}};z-index:9;"></div><div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{textOnLight}}" data-line-height="1.5" data-placement="left-top" data-z-index="32" style="width:100%;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{textOnLight}};line-height:1.5;z-index:32;overflow-wrap:anywhere;">{{pt1}}</div></div>
    <div style="flex:1;min-width:0;"><div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="9" style="width:28px;height:3px;margin-bottom:10px;background:{{secondary}};z-index:9;"></div><div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{textOnLight}}" data-line-height="1.5" data-placement="left-top" data-z-index="33" style="width:100%;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{textOnLight}};line-height:1.5;z-index:33;overflow-wrap:anywhere;">{{pt2}}</div></div>
    <div style="flex:1;min-width:0;"><div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="9" style="width:28px;height:3px;margin-bottom:10px;background:{{secondary}};z-index:9;"></div><div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{textOnLight}}" data-line-height="1.5" data-placement="left-top" data-z-index="34" style="width:100%;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{textOnLight}};line-height:1.5;z-index:34;overflow-wrap:anywhere;">{{pt3}}</div></div>
  </div>
</section>`;
