/**
 * Wave-2：每 pageType +1 套签名（taste + webppt-slide-html）
 * 约束：1000×562.5；data-*↔CSS；无 transform；分隔线用 shape 不用 CSS border。
 */

/** Signature: 底黄铜地台托住标题，画面重心下沉 */
export const HERO_FLOOR = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" data-bg-image-key="{{bgImageKey}}" data-bg-image-prompt="{{bgImagePrompt}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;font-family:{{fontTitle}},serif;">
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{scrim}}" data-z-index="25" style="position:absolute;left:44px;top:32px;width:420px;height:36px;background:{{scrim}};z-index:25;"></div>
  <div data-element="1" data-type="text" data-font-size="10" data-font-family="{{fontBody}}" data-color="{{eyebrow}}" data-line-height="1.3" data-placement="left-top" data-z-index="30" translate="no" style="position:absolute;left:56px;top:44px;width:480px;font-size:10px;font-family:{{fontBody}},sans-serif;letter-spacing:0.28em;color:{{eyebrow}};line-height:1.3;z-index:30;">{{footer}}</div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="5" style="position:absolute;left:0;bottom:0;width:100%;height:168px;background:{{secondary}};z-index:5;"></div>
  <div data-element="1" data-type="text" data-font-size="56" data-font-family="{{fontTitle}}" data-color="{{textOnDark}}" data-line-height="1.08" data-placement="left-bottom" data-bold data-z-index="31" style="position:absolute;left:56px;bottom:196px;width:820px;font-size:56px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnDark}};line-height:1.08;z-index:31;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div data-element="1" data-type="text" data-font-size="15" data-font-family="{{fontBody}}" data-color="{{primaryText}}" data-line-height="1.6" data-placement="left-top" data-z-index="32" style="position:absolute;left:56px;bottom:52px;width:640px;font-size:15px;font-family:{{fontBody}},sans-serif;color:{{primaryText}};line-height:1.6;z-index:32;text-wrap:pretty;overflow-wrap:anywhere;">{{subtitle}}</div>
</section>`;

/** Signature: 四列竖排议程，编号压在列顶 */
export const AGENDA_COLUMNS = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;padding:44px 56px;font-family:{{fontTitle}},sans-serif;">
  <div data-element="1" data-type="text" data-font-size="11" data-font-family="{{fontBody}}" data-color="{{accentText}}" data-line-height="1.3" data-placement="left-top" data-z-index="28" translate="no" style="width:200px;font-size:11px;font-family:{{fontBody}},sans-serif;letter-spacing:0.18em;color:{{accentText}};line-height:1.3;z-index:28;">AGENDA</div>
  <div data-element="1" data-type="text" data-font-size="32" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.2" data-placement="left-top" data-bold data-z-index="30" style="width:888px;margin-top:8px;font-size:32px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.2;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div style="display:flex;gap:0;margin-top:40px;width:888px;align-items:stretch;">
    <div style="flex:1;min-width:0;padding-right:20px;box-sizing:border-box;">
      <div data-element="1" data-type="text" data-font-size="36" data-font-family="{{fontNumeric}}" data-color="{{accentText}}" data-line-height="1" data-placement="left-top" data-bold data-z-index="28" style="width:64px;font-size:36px;font-family:{{fontNumeric}},serif;font-weight:700;color:{{accentText}};line-height:1;z-index:28;font-variant-numeric:tabular-nums;">01</div>
      <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="10" style="width:40px;height:3px;margin-top:16px;background:{{secondary}};z-index:10;"></div>
      <div data-element="1" data-type="text" data-font-size="16" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.3" data-placement="left-top" data-bold data-z-index="30" style="width:100%;margin-top:18px;font-size:16px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.3;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{i1.title}}</div>
      <div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="31" style="width:100%;margin-top:10px;font-size:13px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:31;overflow-wrap:anywhere;">{{i1.body}}</div>
    </div>
    <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{divider}}" data-z-index="9" style="width:1px;align-self:stretch;min-height:280px;background:{{divider}};z-index:9;flex-shrink:0;"></div>
    <div style="flex:1;min-width:0;padding:0 20px;box-sizing:border-box;">
      <div data-element="1" data-type="text" data-font-size="36" data-font-family="{{fontNumeric}}" data-color="{{accentText}}" data-line-height="1" data-placement="left-top" data-bold data-z-index="28" style="width:64px;font-size:36px;font-family:{{fontNumeric}},serif;font-weight:700;color:{{accentText}};line-height:1;z-index:28;font-variant-numeric:tabular-nums;">02</div>
      <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="10" style="width:40px;height:3px;margin-top:16px;background:{{secondary}};z-index:10;"></div>
      <div data-element="1" data-type="text" data-font-size="16" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.3" data-placement="left-top" data-bold data-z-index="30" style="width:100%;margin-top:18px;font-size:16px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.3;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{i2.title}}</div>
      <div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="31" style="width:100%;margin-top:10px;font-size:13px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:31;overflow-wrap:anywhere;">{{i2.body}}</div>
    </div>
    <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{divider}}" data-z-index="9" style="width:1px;align-self:stretch;min-height:280px;background:{{divider}};z-index:9;flex-shrink:0;"></div>
    <div style="flex:1;min-width:0;padding:0 20px;box-sizing:border-box;">
      <div data-element="1" data-type="text" data-font-size="36" data-font-family="{{fontNumeric}}" data-color="{{accentText}}" data-line-height="1" data-placement="left-top" data-bold data-z-index="28" style="width:64px;font-size:36px;font-family:{{fontNumeric}},serif;font-weight:700;color:{{accentText}};line-height:1;z-index:28;font-variant-numeric:tabular-nums;">03</div>
      <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="10" style="width:40px;height:3px;margin-top:16px;background:{{secondary}};z-index:10;"></div>
      <div data-element="1" data-type="text" data-font-size="16" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.3" data-placement="left-top" data-bold data-z-index="30" style="width:100%;margin-top:18px;font-size:16px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.3;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{i3.title}}</div>
      <div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="31" style="width:100%;margin-top:10px;font-size:13px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:31;overflow-wrap:anywhere;">{{i3.body}}</div>
    </div>
    <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{divider}}" data-z-index="9" style="width:1px;align-self:stretch;min-height:280px;background:{{divider}};z-index:9;flex-shrink:0;"></div>
    <div style="flex:1;min-width:0;padding-left:20px;box-sizing:border-box;">
      <div data-element="1" data-type="text" data-font-size="36" data-font-family="{{fontNumeric}}" data-color="{{accentText}}" data-line-height="1" data-placement="left-top" data-bold data-z-index="28" style="width:64px;font-size:36px;font-family:{{fontNumeric}},serif;font-weight:700;color:{{accentText}};line-height:1;z-index:28;font-variant-numeric:tabular-nums;">04</div>
      <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="10" style="width:40px;height:3px;margin-top:16px;background:{{secondary}};z-index:10;"></div>
      <div data-element="1" data-type="text" data-font-size="16" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.3" data-placement="left-top" data-bold data-z-index="30" style="width:100%;margin-top:18px;font-size:16px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.3;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{i4.title}}</div>
      <div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="31" style="width:100%;margin-top:10px;font-size:13px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:31;overflow-wrap:anywhere;">{{i4.body}}</div>
    </div>
  </div>
</section>`;

/** Signature: 左黄铜竖轨锚定问题叙事 */
export const PROBLEM_RAIL = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;font-family:{{fontTitle}},sans-serif;">
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="8" style="position:absolute;left:56px;top:44px;width:5px;height:420px;background:{{secondary}};z-index:8;"></div>
  <div data-element="1" data-type="text" data-font-size="11" data-font-family="{{fontBody}}" data-color="{{accentText}}" data-line-height="1.3" data-placement="left-top" data-z-index="28" translate="no" style="position:absolute;left:84px;top:44px;width:200px;font-size:11px;font-family:{{fontBody}},sans-serif;letter-spacing:0.18em;color:{{accentText}};line-height:1.3;z-index:28;">THE PROBLEM</div>
  <div data-element="1" data-type="text" data-font-size="30" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.22" data-placement="left-top" data-bold data-z-index="30" style="position:absolute;left:84px;top:72px;width:400px;font-size:34px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.152;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.65" data-placement="left-top" data-z-index="31" style="position:absolute;left:84px;top:220px;width:360px;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.65;z-index:31;text-wrap:pretty;overflow-wrap:anywhere;">{{body}}</div>
  <div style="position:absolute;left:520px;top:120px;width:424px;display:flex;flex-direction:column;gap:0;">
    <div style="padding:16px 0;"><div data-element="1" data-type="text" data-font-size="15" data-font-family="{{fontBody}}" data-color="{{textOnLight}}" data-line-height="1.55" data-placement="left-top" data-z-index="32" style="width:100%;font-size:15px;font-family:{{fontBody}},sans-serif;color:{{textOnLight}};line-height:1.55;z-index:32;overflow-wrap:anywhere;">{{pt1}}</div></div>
    <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{hairline}}" data-z-index="8" style="width:100%;height:1px;background:{{hairline}};z-index:8;"></div>
    <div style="padding:16px 0;"><div data-element="1" data-type="text" data-font-size="15" data-font-family="{{fontBody}}" data-color="{{textOnLight}}" data-line-height="1.55" data-placement="left-top" data-z-index="33" style="width:100%;font-size:15px;font-family:{{fontBody}},sans-serif;color:{{textOnLight}};line-height:1.55;z-index:33;overflow-wrap:anywhere;">{{pt2}}</div></div>
    <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{hairline}}" data-z-index="8" style="width:100%;height:1px;background:{{hairline}};z-index:8;"></div>
    <div style="padding:16px 0;"><div data-element="1" data-type="text" data-font-size="15" data-font-family="{{fontBody}}" data-color="{{textOnLight}}" data-line-height="1.55" data-placement="left-top" data-z-index="34" style="width:100%;font-size:15px;font-family:{{fontBody}},sans-serif;color:{{textOnLight}};line-height:1.55;z-index:34;overflow-wrap:anywhere;">{{pt3}}</div></div>
  </div>
</section>`;

/** Signature: 瀑布方案 — 首步全宽，后两步并排 */
export const SOLUTION_CASCADE = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;padding:44px 56px;font-family:{{fontTitle}},sans-serif;">
  <div data-element="1" data-type="text" data-font-size="11" data-font-family="{{fontBody}}" data-color="{{accentText}}" data-line-height="1.3" data-placement="left-top" data-z-index="28" translate="no" style="width:200px;font-size:11px;font-family:{{fontBody}},sans-serif;letter-spacing:0.18em;color:{{accentText}};line-height:1.3;z-index:28;">SOLUTION</div>
  <div data-element="1" data-type="text" data-font-size="32" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.2" data-placement="left-top" data-bold data-z-index="30" style="width:888px;margin-top:8px;font-size:32px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.2;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div style="margin-top:28px;width:888px;">
    <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="10" style="width:48px;height:3px;background:{{secondary}};z-index:10;"></div>
    <div style="display:flex;gap:24px;align-items:baseline;margin-top:16px;">
      <div data-element="1" data-type="text" data-font-size="40" data-font-family="{{fontNumeric}}" data-color="{{accentText}}" data-line-height="1" data-placement="left-top" data-bold data-z-index="28" style="width:72px;flex-shrink:0;font-size:40px;font-family:{{fontNumeric}},serif;font-weight:700;color:{{accentText}};line-height:1;z-index:28;font-variant-numeric:tabular-nums;">01</div>
      <div style="flex:1;min-width:0;">
        <div data-element="1" data-type="text" data-font-size="20" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.3" data-placement="left-top" data-bold data-z-index="30" style="width:100%;font-size:20px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.3;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{s1.title}}</div>
        <div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="31" style="width:100%;margin-top:8px;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:31;overflow-wrap:anywhere;">{{s1.body}}</div>
      </div>
    </div>
  </div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{hairline}}" data-z-index="8" style="width:888px;height:1px;margin-top:28px;background:{{hairline}};z-index:8;"></div>
  <div style="display:flex;gap:40px;margin-top:28px;width:888px;">
    <div style="flex:1;min-width:0;">
      <div data-element="1" data-type="text" data-font-size="28" data-font-family="{{fontNumeric}}" data-color="{{accentText}}" data-line-height="1" data-placement="left-top" data-bold data-z-index="28" style="width:56px;font-size:28px;font-family:{{fontNumeric}},serif;font-weight:700;color:{{accentText}};line-height:1;z-index:28;font-variant-numeric:tabular-nums;">02</div>
      <div data-element="1" data-type="text" data-font-size="17" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.3" data-placement="left-top" data-bold data-z-index="30" style="width:100%;margin-top:12px;font-size:17px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.3;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{s2.title}}</div>
      <div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="31" style="width:100%;margin-top:8px;font-size:13px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:31;overflow-wrap:anywhere;">{{s2.body}}</div>
    </div>
    <div style="flex:1;min-width:0;">
      <div data-element="1" data-type="text" data-font-size="28" data-font-family="{{fontNumeric}}" data-color="{{accentText}}" data-line-height="1" data-placement="left-top" data-bold data-z-index="28" style="width:56px;font-size:28px;font-family:{{fontNumeric}},serif;font-weight:700;color:{{accentText}};line-height:1;z-index:28;font-variant-numeric:tabular-nums;">03</div>
      <div data-element="1" data-type="text" data-font-size="17" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.3" data-placement="left-top" data-bold data-z-index="30" style="width:100%;margin-top:12px;font-size:17px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.3;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{s3.title}}</div>
      <div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="31" style="width:100%;margin-top:8px;font-size:13px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:31;overflow-wrap:anywhere;">{{s3.body}}</div>
    </div>
  </div>
</section>`;

/** Signature: 左桅杆标题区 + 右三要点纵列 */
export const PILLARS_MAST = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;font-family:{{fontTitle}},sans-serif;">
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{primary}}" data-z-index="5" style="position:absolute;left:0;top:0;width:340px;height:100%;background:{{primary}};z-index:5;"></div>
  <div data-element="1" data-type="text" data-font-size="11" data-font-family="{{fontBody}}" data-color="{{accentOnPrimary}}" data-line-height="1.3" data-placement="left-top" data-z-index="28" translate="no" style="position:absolute;left:48px;top:48px;width:240px;font-size:11px;font-family:{{fontBody}},sans-serif;letter-spacing:0.18em;color:{{accentOnPrimary}};line-height:1.3;z-index:28;">FOCUS AREAS</div>
  <div data-element="1" data-type="text" data-font-size="28" data-font-family="{{fontTitle}}" data-color="{{textOnDark}}" data-line-height="1.25" data-placement="left-top" data-bold data-z-index="30" style="position:absolute;left:48px;top:200px;width:250px;font-size:28px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnDark}};line-height:1.25;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div style="position:absolute;left:400px;top:72px;width:544px;display:flex;flex-direction:column;gap:0;">
    <div style="display:flex;gap:16px;align-items:flex-start;padding:18px 0;">
      <div data-element="1" data-type="icon" aria-hidden="true" data-icon-name="{{p1.iconName}}" data-icon-theme="outline" data-fill="{{secondary}}" data-stroke-width="3" data-z-index="29" style="width:28px;height:28px;z-index:29;flex-shrink:0;"></div>
      <div style="flex:1;min-width:0;"><div data-element="1" data-type="text" data-font-size="17" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.3" data-placement="left-top" data-bold data-z-index="30" style="width:100%;font-size:17px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.3;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{p1.title}}</div><div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="31" style="width:100%;margin-top:6px;font-size:13px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:31;overflow-wrap:anywhere;">{{p1.body}}</div></div>
    </div>
    <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{hairline}}" data-z-index="8" style="width:100%;height:1px;background:{{hairline}};z-index:8;"></div>
    <div style="display:flex;gap:16px;align-items:flex-start;padding:18px 0;">
      <div data-element="1" data-type="icon" aria-hidden="true" data-icon-name="{{p2.iconName}}" data-icon-theme="outline" data-fill="{{secondary}}" data-stroke-width="3" data-z-index="29" style="width:28px;height:28px;z-index:29;flex-shrink:0;"></div>
      <div style="flex:1;min-width:0;"><div data-element="1" data-type="text" data-font-size="17" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.3" data-placement="left-top" data-bold data-z-index="30" style="width:100%;font-size:17px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.3;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{p2.title}}</div><div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="31" style="width:100%;margin-top:6px;font-size:13px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:31;overflow-wrap:anywhere;">{{p2.body}}</div></div>
    </div>
    <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{hairline}}" data-z-index="8" style="width:100%;height:1px;background:{{hairline}};z-index:8;"></div>
    <div style="display:flex;gap:16px;align-items:flex-start;padding:18px 0;">
      <div data-element="1" data-type="icon" aria-hidden="true" data-icon-name="{{p3.iconName}}" data-icon-theme="outline" data-fill="{{secondary}}" data-stroke-width="3" data-z-index="29" style="width:28px;height:28px;z-index:29;flex-shrink:0;"></div>
      <div style="flex:1;min-width:0;"><div data-element="1" data-type="text" data-font-size="17" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.3" data-placement="left-top" data-bold data-z-index="30" style="width:100%;font-size:17px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.3;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{p3.title}}</div><div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="31" style="width:100%;margin-top:6px;font-size:13px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:31;overflow-wrap:anywhere;">{{p3.body}}</div></div>
    </div>
  </div>
</section>`;

/** Signature: 主指标占左上角，辅两项沉底横排 */
export const METRICS_CORNER = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;font-family:{{fontTitle}},sans-serif;">
  <div data-element="1" data-type="text" data-font-size="32" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.2" data-placement="left-top" data-bold data-z-index="30" style="position:absolute;left:56px;top:44px;width:888px;font-size:32px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.2;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="10" style="position:absolute;left:56px;top:120px;width:48px;height:3px;background:{{secondary}};z-index:10;"></div>
  <div data-element="1" data-type="text" data-font-size="96" data-font-family="{{fontNumeric}}" data-color="{{primaryText}}" data-line-height="1" data-placement="left-top" data-bold data-z-index="30" style="position:absolute;left:56px;top:148px;width:480px;font-size:96px;font-family:{{fontNumeric}},serif;font-weight:700;color:{{primaryText}};line-height:1;z-index:30;font-variant-numeric:tabular-nums;overflow-wrap:anywhere;">{{m1.value}}</div>
  <div data-element="1" data-type="text" data-font-size="15" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.5" data-placement="left-top" data-z-index="31" style="position:absolute;left:56px;top:268px;width:400px;font-size:15px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.5;z-index:31;overflow-wrap:anywhere;">{{m1.label}}</div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{primary}}" data-z-index="5" style="position:absolute;left:0;bottom:0;width:100%;height:160px;background:{{primary}};z-index:5;"></div>
  <div style="position:absolute;left:56px;bottom:48px;width:888px;display:flex;gap:48px;z-index:20;">
    <div style="flex:1;min-width:0;"><div data-element="1" data-type="text" data-font-size="40" data-font-family="{{fontNumeric}}" data-color="{{textOnDark}}" data-line-height="1" data-placement="left-top" data-bold data-z-index="30" style="width:100%;font-size:40px;font-family:{{fontNumeric}},serif;font-weight:700;color:{{textOnDark}};line-height:1;z-index:30;font-variant-numeric:tabular-nums;overflow-wrap:anywhere;">{{m2.value}}</div><div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontBody}}" data-color="{{textOnDark}}" data-line-height="1.45" data-placement="left-top" data-z-index="31" style="width:100%;margin-top:10px;font-size:13px;font-family:{{fontBody}},sans-serif;color:{{textOnDark}};line-height:1.45;z-index:31;overflow-wrap:anywhere;">{{m2.label}}</div></div>
    <div style="flex:1;min-width:0;"><div data-element="1" data-type="text" data-font-size="40" data-font-family="{{fontNumeric}}" data-color="{{textOnDark}}" data-line-height="1" data-placement="left-top" data-bold data-z-index="32" style="width:100%;font-size:40px;font-family:{{fontNumeric}},serif;font-weight:700;color:{{textOnDark}};line-height:1;z-index:32;font-variant-numeric:tabular-nums;overflow-wrap:anywhere;">{{m3.value}}</div><div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontBody}}" data-color="{{textOnDark}}" data-line-height="1.45" data-placement="left-top" data-z-index="33" style="width:100%;margin-top:10px;font-size:13px;font-family:{{fontBody}},sans-serif;color:{{textOnDark}};line-height:1.45;z-index:33;overflow-wrap:anywhere;">{{m3.label}}</div></div>
    <div style="flex:1.2;min-width:0;display:flex;align-items:flex-end;"><div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontBody}}" data-color="{{primaryInk}}" data-line-height="1.5" data-placement="left-top" data-z-index="34" style="width:100%;font-size:13px;font-family:{{fontBody}},sans-serif;color:{{primaryInk}};line-height:1.5;z-index:34;text-wrap:pretty;overflow-wrap:anywhere;">{{footer}}</div></div>
  </div>
</section>`;

/** Signature: 证据作巨型引语，下方编号解读 */
export const EVIDENCE_QUOTE = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;padding:44px 56px;font-family:{{fontTitle}},sans-serif;">
  <div data-element="1" data-type="text" data-font-size="24" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.25" data-placement="left-top" data-bold data-z-index="30" style="width:888px;font-size:24px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.25;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div style="display:flex;gap:20px;align-items:stretch;margin-top:28px;width:888px;">
    <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="8" style="width:5px;align-self:stretch;min-height:100px;background:{{secondary}};z-index:8;flex-shrink:0;"></div>
    <div data-element="1" data-type="text" data-font-size="22" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.45" data-placement="left-top" data-bold data-z-index="31" style="flex:1;min-width:0;font-size:22px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.45;z-index:31;text-wrap:balance;overflow-wrap:anywhere;">{{caption}}</div>
  </div>
  <div style="display:flex;gap:28px;margin-top:40px;width:888px;">
    <div style="flex:1;min-width:0;"><div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontNumeric}}" data-color="{{accentText}}" data-line-height="1" data-placement="left-top" data-bold data-z-index="28" style="width:40px;font-size:13px;font-family:{{fontNumeric}},serif;font-weight:700;color:{{accentText}};line-height:1;z-index:28;font-variant-numeric:tabular-nums;">01</div><div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="32" style="width:100%;margin-top:10px;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:32;overflow-wrap:anywhere;">{{b1}}</div></div>
    <div style="flex:1;min-width:0;"><div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontNumeric}}" data-color="{{accentText}}" data-line-height="1" data-placement="left-top" data-bold data-z-index="28" style="width:40px;font-size:13px;font-family:{{fontNumeric}},serif;font-weight:700;color:{{accentText}};line-height:1;z-index:28;font-variant-numeric:tabular-nums;">02</div><div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="33" style="width:100%;margin-top:10px;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:33;overflow-wrap:anywhere;">{{b2}}</div></div>
    <div style="flex:1;min-width:0;"><div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontNumeric}}" data-color="{{accentText}}" data-line-height="1" data-placement="left-top" data-bold data-z-index="28" style="width:40px;font-size:13px;font-family:{{fontNumeric}},serif;font-weight:700;color:{{accentText}};line-height:1;z-index:28;font-variant-numeric:tabular-nums;">03</div><div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="34" style="width:100%;margin-top:10px;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:34;overflow-wrap:anywhere;">{{b3}}</div></div>
  </div>
</section>`;

/** Signature: 左墨板 / 右浅板双面对照 */
export const COMPARE_PANELS = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;font-family:{{fontTitle}},sans-serif;">
  <div data-element="1" data-type="text" data-font-size="32" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.2" data-placement="left-top" data-bold data-z-index="30" style="position:absolute;left:56px;top:36px;width:888px;font-size:32px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.2;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{primary}}" data-z-index="5" style="position:absolute;left:56px;top:100px;width:420px;height:400px;background:{{primary}};z-index:5;"></div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="6" style="position:absolute;left:56px;top:100px;width:420px;height:4px;background:{{secondary}};z-index:6;"></div>
  <div data-element="1" data-type="text" data-font-size="20" data-font-family="{{fontTitle}}" data-color="{{textOnDark}}" data-line-height="1.3" data-placement="left-top" data-bold data-z-index="30" style="position:absolute;left:88px;top:140px;width:356px;font-size:20px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnDark}};line-height:1.3;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{leftTitle}}</div>
  <div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{textOnDark}}" data-line-height="1.65" data-placement="left-top" data-z-index="31" style="position:absolute;left:88px;top:220px;width:356px;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{textOnDark}};line-height:1.65;z-index:31;overflow-wrap:anywhere;">{{leftBody}}</div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{cardFill}}" data-z-index="5" style="position:absolute;right:56px;top:100px;width:420px;height:400px;background:{{cardFill}};z-index:5;"></div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="6" style="position:absolute;right:56px;top:100px;width:420px;height:4px;background:{{secondary}};z-index:6;"></div>
  <div data-element="1" data-type="text" data-font-size="20" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.3" data-placement="left-top" data-bold data-z-index="30" style="position:absolute;right:88px;top:140px;width:356px;font-size:20px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.3;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{rightTitle}}</div>
  <div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.65" data-placement="left-top" data-z-index="31" style="position:absolute;right:88px;top:220px;width:356px;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.65;z-index:31;overflow-wrap:anywhere;">{{rightBody}}</div>
</section>`;

/** Signature: 金句贴上，归属沉入底黄铜带 */
export const BREATH_FLOOR = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;font-family:{{fontTitle}},sans-serif;">
  <div data-element="1" data-type="text" data-font-size="36" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.35" data-placement="left-center" data-bold data-z-index="30" style="position:absolute;left:56px;top:140px;width:760px;font-size:36px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.35;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{quote}}</div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="5" style="position:absolute;left:0;bottom:0;width:100%;height:96px;background:{{secondary}};z-index:5;"></div>
  <div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontBody}}" data-color="{{secondaryInk}}" data-line-height="1.4" data-placement="left-top" data-z-index="31" style="position:absolute;left:56px;bottom:38px;width:700px;font-size:13px;font-family:{{fontBody}},sans-serif;letter-spacing:0.06em;color:{{secondaryInk}};line-height:1.4;z-index:31;overflow-wrap:anywhere;">{{attribution}}</div>
</section>`;

/** Signature: 姓名作主信号，角色作小号眉题 */
export const TEAM_MAST = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;padding:44px 56px;font-family:{{fontTitle}},sans-serif;">
  <div data-element="1" data-type="text" data-font-size="32" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.2" data-placement="left-top" data-bold data-z-index="30" style="width:888px;font-size:32px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.2;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div style="display:flex;gap:0;margin-top:48px;width:888px;align-items:stretch;">
    <div style="flex:1;min-width:0;padding-right:28px;box-sizing:border-box;">
      <div data-element="1" data-type="text" data-font-size="11" data-font-family="{{fontBody}}" data-color="{{accentText}}" data-line-height="1.3" data-placement="left-top" data-z-index="28" translate="no" style="width:100%;font-size:11px;font-family:{{fontBody}},sans-serif;letter-spacing:0.14em;color:{{accentText}};line-height:1.3;z-index:28;">{{tm1.role}}</div>
      <div data-element="1" data-type="text" data-font-size="28" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.2" data-placement="left-top" data-bold data-z-index="30" style="width:100%;margin-top:12px;font-size:28px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.2;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{tm1.name}}</div>
      <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="10" style="width:40px;height:3px;margin-top:18px;background:{{secondary}};z-index:10;"></div>
      <div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="31" style="width:100%;margin-top:16px;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:31;overflow-wrap:anywhere;">{{tm1.blurb}}</div>
    </div>
    <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{divider}}" data-z-index="9" style="width:1px;align-self:stretch;min-height:280px;background:{{divider}};z-index:9;flex-shrink:0;"></div>
    <div style="flex:1;min-width:0;padding:0 28px;box-sizing:border-box;">
      <div data-element="1" data-type="text" data-font-size="11" data-font-family="{{fontBody}}" data-color="{{accentText}}" data-line-height="1.3" data-placement="left-top" data-z-index="28" translate="no" style="width:100%;font-size:11px;font-family:{{fontBody}},sans-serif;letter-spacing:0.14em;color:{{accentText}};line-height:1.3;z-index:28;">{{tm2.role}}</div>
      <div data-element="1" data-type="text" data-font-size="28" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.2" data-placement="left-top" data-bold data-z-index="30" style="width:100%;margin-top:12px;font-size:28px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.2;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{tm2.name}}</div>
      <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="10" style="width:40px;height:3px;margin-top:18px;background:{{secondary}};z-index:10;"></div>
      <div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="31" style="width:100%;margin-top:16px;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:31;overflow-wrap:anywhere;">{{tm2.blurb}}</div>
    </div>
    <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{divider}}" data-z-index="9" style="width:1px;align-self:stretch;min-height:280px;background:{{divider}};z-index:9;flex-shrink:0;"></div>
    <div style="flex:1;min-width:0;padding-left:28px;box-sizing:border-box;">
      <div data-element="1" data-type="text" data-font-size="11" data-font-family="{{fontBody}}" data-color="{{accentText}}" data-line-height="1.3" data-placement="left-top" data-z-index="28" translate="no" style="width:100%;font-size:11px;font-family:{{fontBody}},sans-serif;letter-spacing:0.14em;color:{{accentText}};line-height:1.3;z-index:28;">{{tm3.role}}</div>
      <div data-element="1" data-type="text" data-font-size="28" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.2" data-placement="left-top" data-bold data-z-index="30" style="width:100%;margin-top:12px;font-size:28px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.2;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{tm3.name}}</div>
      <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="10" style="width:40px;height:3px;margin-top:18px;background:{{secondary}};z-index:10;"></div>
      <div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.55" data-placement="left-top" data-z-index="31" style="width:100%;margin-top:16px;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.55;z-index:31;overflow-wrap:anywhere;">{{tm3.blurb}}</div>
    </div>
  </div>
</section>`;

/** Signature: 四阶段顶标 + 连续黄铜轴（非色带底） */
export const TIMELINE_MAST = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;padding:44px 56px;font-family:{{fontTitle}},sans-serif;">
  <div data-element="1" data-type="text" data-font-size="32" data-font-family="{{fontTitle}}" data-color="{{textOnLight}}" data-line-height="1.2" data-placement="left-top" data-bold data-z-index="30" style="width:888px;font-size:32px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnLight}};line-height:1.2;z-index:30;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="8" style="width:888px;height:3px;margin-top:72px;background:{{secondary}};z-index:8;"></div>
  <div style="display:flex;gap:24px;margin-top:-14px;width:888px;">
    <div style="flex:1;min-width:0;"><div data-element="1" data-type="shape" data-shape-type="oval" data-fill="{{secondary}}" data-z-index="20" style="width:14px;height:14px;background:{{secondary}};border-radius:50%;z-index:20;"></div><div data-element="1" data-type="text" data-font-size="16" data-font-family="{{fontTitle}}" data-color="{{accentText}}" data-line-height="1.3" data-placement="left-top" data-bold data-z-index="30" translate="no" style="width:100%;margin-top:24px;font-size:16px;font-family:{{fontTitle}},sans-serif;font-weight:700;color:{{accentText}};line-height:1.3;z-index:30;">{{t1.label}}</div><div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.5" data-placement="left-top" data-z-index="31" style="width:100%;margin-top:8px;font-size:13px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.5;z-index:31;overflow-wrap:anywhere;">{{t1.detail}}</div></div>
    <div style="flex:1;min-width:0;"><div data-element="1" data-type="shape" data-shape-type="oval" data-fill="{{secondary}}" data-z-index="20" style="width:14px;height:14px;background:{{secondary}};border-radius:50%;z-index:20;"></div><div data-element="1" data-type="text" data-font-size="16" data-font-family="{{fontTitle}}" data-color="{{accentText}}" data-line-height="1.3" data-placement="left-top" data-bold data-z-index="30" translate="no" style="width:100%;margin-top:24px;font-size:16px;font-family:{{fontTitle}},sans-serif;font-weight:700;color:{{accentText}};line-height:1.3;z-index:30;">{{t2.label}}</div><div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.5" data-placement="left-top" data-z-index="31" style="width:100%;margin-top:8px;font-size:13px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.5;z-index:31;overflow-wrap:anywhere;">{{t2.detail}}</div></div>
    <div style="flex:1;min-width:0;"><div data-element="1" data-type="shape" data-shape-type="oval" data-fill="{{secondary}}" data-z-index="20" style="width:14px;height:14px;background:{{secondary}};border-radius:50%;z-index:20;"></div><div data-element="1" data-type="text" data-font-size="16" data-font-family="{{fontTitle}}" data-color="{{accentText}}" data-line-height="1.3" data-placement="left-top" data-bold data-z-index="30" translate="no" style="width:100%;margin-top:24px;font-size:16px;font-family:{{fontTitle}},sans-serif;font-weight:700;color:{{accentText}};line-height:1.3;z-index:30;">{{t3.label}}</div><div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.5" data-placement="left-top" data-z-index="31" style="width:100%;margin-top:8px;font-size:13px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.5;z-index:31;overflow-wrap:anywhere;">{{t3.detail}}</div></div>
    <div style="flex:1;min-width:0;"><div data-element="1" data-type="shape" data-shape-type="oval" data-fill="{{secondary}}" data-z-index="20" style="width:14px;height:14px;background:{{secondary}};border-radius:50%;z-index:20;"></div><div data-element="1" data-type="text" data-font-size="16" data-font-family="{{fontTitle}}" data-color="{{accentText}}" data-line-height="1.3" data-placement="left-top" data-bold data-z-index="30" translate="no" style="width:100%;margin-top:24px;font-size:16px;font-family:{{fontTitle}},sans-serif;font-weight:700;color:{{accentText}};line-height:1.3;z-index:30;">{{t4.label}}</div><div data-element="1" data-type="text" data-font-size="13" data-font-family="{{fontBody}}" data-color="{{muted}}" data-line-height="1.5" data-placement="left-top" data-z-index="31" style="width:100%;margin-top:8px;font-size:13px;font-family:{{fontBody}},sans-serif;color:{{muted}};line-height:1.5;z-index:31;overflow-wrap:anywhere;">{{t4.detail}}</div></div>
  </div>
</section>`;

/** Signature: 四角框线 + 底黄铜地台收束 */
export const CLOSE_FLOOR = `<section id="slide" data-page-id="{{pageId}}" data-bg="{{background}}" data-bg-image-key="{{bgImageKey}}" data-bg-image-prompt="{{bgImagePrompt}}" style="width:1000px;height:562.5px;position:relative;overflow:hidden;background:{{background}};box-sizing:border-box;font-family:{{fontTitle}},sans-serif;">
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="6" style="position:absolute;left:48px;top:88px;width:48px;height:3px;background:{{secondary}};z-index:6;"></div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="6" style="position:absolute;left:48px;top:88px;width:3px;height:48px;background:{{secondary}};z-index:6;"></div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="6" style="position:absolute;right:48px;top:88px;width:48px;height:3px;background:{{secondary}};z-index:6;"></div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="6" style="position:absolute;right:48px;top:88px;width:3px;height:48px;background:{{secondary}};z-index:6;"></div>
  <div data-element="1" data-type="text" data-font-size="44" data-font-family="{{fontTitle}}" data-color="{{textOnDark}}" data-line-height="1.14" data-placement="left-center" data-bold data-z-index="31" style="position:absolute;left:72px;top:200px;width:720px;font-size:44px;font-family:{{fontTitle}},serif;font-weight:700;color:{{textOnDark}};line-height:1.14;z-index:31;text-wrap:balance;overflow-wrap:anywhere;">{{title}}</div>
  <div data-element="1" data-type="shape" data-shape-type="rect" data-fill="{{secondary}}" data-z-index="5" style="position:absolute;left:0;bottom:0;width:100%;height:120px;background:{{secondary}};z-index:5;"></div>
  <div data-element="1" data-type="text" data-font-size="14" data-font-family="{{fontBody}}" data-color="{{primaryText}}" data-line-height="1.5" data-placement="left-top" data-z-index="32" style="position:absolute;left:56px;bottom:64px;width:560px;font-size:14px;font-family:{{fontBody}},sans-serif;color:{{primaryText}};line-height:1.5;z-index:32;text-wrap:pretty;overflow-wrap:anywhere;">{{subtitle}}</div>
  <div data-element="1" data-type="text" data-font-size="12" data-font-family="{{fontBody}}" data-color="{{primaryText}}" data-line-height="1.4" data-placement="left-top" data-z-index="33" translate="no" style="position:absolute;left:56px;bottom:32px;width:560px;font-size:12px;font-family:{{fontBody}},sans-serif;letter-spacing:0.08em;color:{{primaryText}};line-height:1.4;z-index:33;overflow-wrap:anywhere;">{{contact}}</div>
</section>`;
